### ISSUE TITLE
Incorrect timedelta when substracting DST and non DST

### ISSUE THREAD

**Issue by smitshah993** [dateutil/dateutil#1001]
Hi,

I am facing the following issue:

dateutil: 2.8.1
Python: Python 3.7.3

```python
>>> import dateutil; print(dateutil.__version__)
2.8.1
>>> import datetime
>>> from dateutil.tz import gettz
>>> time_a = datetime.datetime(2020,3,7,19,40, tzinfo=gettz("America/Toronto"))
>>> time_b = datetime.datetime(2020,3,8,7,40, tzinfo=gettz("America/Toronto"))
>>> time_a.isoformat()
'2020-03-07T19:40:00-05:00'
>>> time_b.isoformat()
'2020-03-08T07:40:00-04:00'
>>> from dateutil.relativedelta import relativedelta
>>> relativedelta(time_b, time_a)
relativedelta(hours=+12)
```

This should be +11 as there was a change in daylight savings time.

**Comment by pganssle** [comment]
@smitshah993 `dateutil.relativedelta.relativedelta` is not intended to be an absolute measure of time between two events - the way you are constructing it, it is more of a "calendar delta". I have written a [blog post about datetime math in Python](https://blog.ganssle.io/articles/2018/02/aware-datetime-arithmetic.html) that may help illustrate the issue for you.

Basically, if you want to know the absolute amount of time that elapsed between those two datetimes, you should convert them to UTC and then subtract (actually, converting *either* of them to UTC is sufficient because of how arithmetic works in Python's `datetime`). The blog post is about the standard `datetime` arithmetic, but `relativedelta` basically is mainly intended to *only* be "wall time" arithmetic (though apparently if you convert one of the datetimes to UTC before passing it to the `relativedelta` constructor you *will* get an absolute elapsed time).

**Comment by sihil** [comment]
This was also a bit surprising for me. Coming from a JVM background I would call these two different deltas by two different names: duration and period. Duration is the absolute elapsed time and period is date based. You can read more about that [in the Java tutorial](https://docs.oracle.com/javase/tutorial/datetime/iso/period.html).

In short, I think both types have valid but disparate use cases. By forcing datetimes to UTC you can more or less get the behaviour of a duration instead of `relativedelta`s default behaviour of calculating a period.

FWIW, the newer Java time library (based on [JSR-310](https://jcp.org/aboutJava/communityprocess/pfd/jsr310/JSR-310-guide.html)) is the only datetime library I've ever used in my career that is hard to use wrong. It's got a learning curve, but it doesn't let you mix up different date, time and delta concepts incorrectly. It seems to have been ported to a number of other languages too including python.

To be fair, it took over 20 years for Java to actually get a library that worked well.
