### ISSUE TITLE
Parser parsing wrong text to date.

### ISSUE THREAD

**Issue by ravi0912** [dateutil/dateutil#1013]
`s = '26 s'
dateutil.parser.parse(s, dayfirst=True)
`
output:
datetime.datetime(2020, 3, 12, 0, 0, 26)
So the dateutil parser parsing the random string to date.

**Comment by ffe4** [comment]
I think what is going on is that your string is interpreted as `26 seconds` and then the rest of the information gets filled in with `datetime.now()`. The `dayfirst` argument does not do anything because there is no 3-integer date like `01/05/09`.

A quote from the [parser docs](https://dateutil.readthedocs.io/en/stable/parser.html):
> This module attempts to be forgiving with regards to unlikely input formats, returning a datetime object even for dates which are ambiguous.
[...]
If any other elements are missing, they are taken from the `datetime.datetime` object passed to the parameter `default`.

If `default` is `None`, it will be set to `datetime.now()` like so:
```python
if default is None:
    default = datetime.datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
```

Depending on what behavior you want, you could use `parser.isoparse` or provide a custom [`parserinfo`](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parserinfo) object, which handles what inputs will be accepted.

Improving the documentation for `parser` is already on the todo list in #666 and this is one of the behaviors that might be useful to explain more explicitly. If you'd like to help, feel free to suggest your own changes.

**Comment by pganssle** [comment]
Yes, thanks @ffe4, I think that's definitely the correct way to think about it.

Also, even if we did want to fix this, I believe a lot of people are relying on the way that `dateutil` parses "XhYmZs", because they'll do things like this to parse a timedelta:

```python
from datetime import datetime
from dateutil.parser import parse

default = datetime(2020, 1, 1)
offset = parse("3h30m", default=default) - default
```

Creating a timedelta parser would be very helpful to separate these concerns, but it would still be a breaking change.
