### ISSUE TITLE
America/Nuuk timezone not recognized

### ISSUE THREAD

**Issue by jadchaar** [dateutil/dateutil#1040]
We were in the process of updating testing dependencies for Arrow (https://github.com/crsmithdev/arrow) and our formatting tests, which run on the entire TZ database, are failing due to dateutil not recognizing the timezone "America/Nuuk". Instead of returning an appropriate `tzfile`, dateutil seems to return `None` instead. This seems to be a symptom of updating `pytz` to version `2020.1`. Below is a snippet of code showing this issue in action:

```shell
venv ❯ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dateutil import tz
>>> tz.gettz("America/Nuuk")
>>> tz.gettz("America/New York")
tzfile('/usr/share/zoneinfo/America/New_York')
```

**Comment by pganssle** [comment]
@jadchaar I assume this is because `America/Nuuk` is new in 2020a, and it was named `America/Godthab` before that. Your local time zone information doesn't contain that zone and we haven't released a version of `dateutil` that has it vendored yet.

This is already "fixed" (to the extent that it needs to be – there's an invalid assumption on the part of your tests here) on the master branch of `dateutil`.
