### ISSUE TITLE
Allow to use system zoneinfo

### ISSUE THREAD

**Issue by Arfrever** [dateutil/dateutil#11]
Dateutil should use system zoneinfo (available in /usr/share/zoneinfo) when dateutil-zoneinfo.tar.gz is not available.

```
--- dateutil/zoneinfo/__init__.py
+++ dateutil/zoneinfo/__init__.py
@@ -14,9 +14,10 @@

 __all__ = ["setcachesize", "gettz", "rebuild"]

-_ZONEFILENAME = "dateutil-zoneinfo.tar.gz"
+_LOCAL_ZONEINFO_FILE = "dateutil-zoneinfo.tar.gz"
+_SYSTEM_ZONEINFO_DIR = "/usr/share/zoneinfo"

-# python2.6 compatability. Note that TarFile.__exit__ != TarFile.close, but
+# python2.6 compatibility. Note that TarFile.__exit__ != TarFile.close, but
 # it's close enough for python2.6
 _tar_open = TarFile.open
 if not hasattr(TarFile, '__exit__'):
@@ -31,9 +32,8 @@

 def getzoneinfofile_stream():
     try:
-        return BytesIO(get_data(__name__, _ZONEFILENAME))
+        return BytesIO(get_data(__name__, _LOCAL_ZONEINFO_FILE))
     except IOError as e:  # TODO  switch to FileNotFoundError?
-        warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
         return None


@@ -59,6 +59,14 @@
                 self.zones.update(links)
         else:
             self.zones = dict()
+            if os.path.isdir(_SYSTEM_ZONEINFO_DIR):
+                for root, dirnames, filenames in os.walk(_SYSTEM_ZONEINFO_DIR):
+                    for filename in filenames:
+                        absolute_filename = os.path.join(root, filename)
+                        relative_filename = absolute_filename[len(_SYSTEM_ZONEINFO_DIR)+1:]
+                        with open(absolute_filename, "rb") as file:
+                            if file.read(4) == b"TZif":
+                                self.zones[relative_filename] = tzfile(absolute_filename, relative_filename)


 # The current API has gettz as a module function, although in fact it taps into
@@ -99,7 +107,7 @@
                         "libc-bin or some other package that provides it, "
                         "or it's not in your PATH?")
                     raise
-        target = os.path.join(moduledir, _ZONEFILENAME)
+        target = os.path.join(moduledir, _LOCAL_ZONEINFO_FILE)
         with _tar_open(target, "w:%s" % format) as tf:
             for entry in os.listdir(zonedir):
                 entrypath = os.path.join(zonedir, entry)
```

**Comment by keszybz** [comment]
I'm looking into this in the context of Fedora packaging. We're trying to update everything to latest dateutil in Fedora 22 (https://bugzilla.redhat.com/show_bug.cgi?id=1126521), and this is one of the issues we encountered.

@jarondl can you clarify that consumers (e.g. pandas) is supposed to be using dateutil.tz.gettz() instead of dateutil.zoneinfo.gettz()?

**Comment by jarondl** [comment]
@keszybz yes, I can try.

**Comment by pganssle** [comment]
@jarondl I'm not sure what the takeaway here is - is the plan to deprecate `zoneinfo.gettz()` entirely, or just add to the documentation the specific time you would use it?

I'm not 100% sure what to deprecate in reference to [this note in gettz()](https://github.com/dateutil/dateutil/blob/master/dateutil/zoneinfo/__init__.py#L81). We should probably deprecate whatever needs to be deprecated before the 2.6.0 release.

**Comment by jarondl** [comment]
Hi @pganssle,
I find the current API somewhat confusing.

1. `tz.gettz()` should be the main way people get timezones, because it tries the system timezones first.
2. `zoneinfo.gettz()` creates a `ZoneInfoFile` instance from the embedded `zoneinfo` file on the first time it is called, and gets the timezones from it. I would prefer it if users simply instantiated the class themselves if they really need it.

So the plan was to:

1. Make sure our main users don't use `zoneinfo.gettz()`. (As you can see in this thread, pandas already switched)
2. Add a deprecation warning for one version. (Say 2.6.0)
3. Remove the function on the next version. (Say 2.7.0)

I haven't got around to do any of the above, and I am not sure if the plan is still relevant. What's your opinion on this?

**Comment by pganssle** [comment]
@jarondl I agree that `tz.gettz()` should be the proper way to get a time zone for sure, though presumably some people will prefer to use dateutil's zoneinfo, so I can see the utility in having the `zoneinfo.gettz()` module function.

I kinda think that this is something that can be solved by being explicit in the documentation so that projects like `pandas` can understand the clear difference between `zoneinfo.gettz()` and `tz.gettz()`.

I don't see this as being so useless that the feature should be dropped entirely, as long as we're clear that it's purely a convenience function, and that if they want to avoid whatever problems that might come up like caching of zoneinfo files, they should instantiate their own ZoneInfoFile object.

@Arfrever @keszybz - Would those clarifications in documentation be agreeable?

**Comment by pganssle** [comment]
Oh, also, from a semantic versioning perspective, I think we should probably increment the major version number if we're going to actually remove existing API functionality, so if we do deprecate `gettz()`, we should add a deprecation warning in 2.6.0 and then when enough time has passed that no one is using it anymore, we can increment to 3.0.0 in a breaking change.

**Comment by keszybz** [comment]
I think one of the main reasons for confusion is that the functions have the same name. And `zoneinfo` and `tz` are also quite similar conceptually, so it's easy to mistake them. When looking at some random code calling `gettz()`, you have to go and look at the imports list to see if the call is correct or not.

I don't have an opinion whether `zoneinfo.gettz` is useful, but I think it should be either removed or renamed in the long run, and calling it under that name should start to emit a deprecation warning before that. Otherwise I fear we'll continue to find it called from various random projects by mistake.

**Comment by pganssle** [comment]
I suppose it's fine to rename it, though I'm not sure it's *so different* from `gettz` that we need to prevent its mistaken use at all costs. People misuse `pytz.localize` and `pytz.normalize` all the time.

Still, I wouldn't be opposed to a long period of deprecation where the function is renamed to something like `get_zoneinfo_tz()`.

**Comment by pganssle** [comment]
OK, I've gone ahead and deprecated this, and introduced a new convenience function that pulls a singleton `ZoneInfoFile` using the `dateutil`-provided tzinfo data. This should make it much more obvious what's going on here.
