### ISSUE TITLE
Parser timestamp generated from strftime is incorrect

### ISSUE THREAD

**Issue by smorar** [dateutil/dateutil#1102]
Steps to reproduce:
```
import dateutil.parser
t = dateutil.parser.parse('2021-01-17T04:52:45Z')
print(t.timestamp())
print(int(t.strftime('%s%f'))/1000000)
```
Output:
```
1610859165.0
1610823165.0
```

The two timestamps output in two different ways should be the same. They arent.
In this case, the timestamp function produces the correct output.

The string formatting function produces an incorrect output.

The difference between these two values seems to be related to the timezone that my PC is set to, which in my case is UTC +10h.

Ubuntu 20.10, package version: python3-dateutil 2.8.1-4

**Comment by smorar** [comment]
To demonstrate that this is timezone setting related, the same code generates the following output when I change my timezone to UTC +2h:
```
1610859165.0
1610851965.0
```

**Comment by pganssle** [comment]
This doesn't really have anything to do with the parser, the parser here is just being used to construct the datetime object.

You can replace the parser call with `datetime.datetime(2021, 1, 17, 4, 52, 45, tzinfo=datetime.timezone.utc)` and it will give you the same results.

I think the issue is that `%s` ignores the tzinfo, though I'm not sure if that's deliberate. The appropriate place for the discussion is bugs.python.org.
