### ISSUE TITLE
Subtracting 3 months from (2021, 7, 30) and (2021, 7, 31) produces the same result

### ISSUE THREAD

**Issue by kemar** [dateutil/dateutil#1134]
Hi,

- `dateutil`: 2.8.1
- `Python`: 3.9.2

Can't wrap my brain around this:

```python
>>> import datetime
>>> from dateutil.relativedelta import relativedelta

>>> datetime.date(2021, 7, 30) - relativedelta(months=3)
datetime.date(2021, 4, 30)

>>> datetime.date(2021, 7, 31) - relativedelta(months=3)
datetime.date(2021, 4, 30)
```

Is this the intended behaviour?

**Comment by pganssle** [comment]
Yes, this is the intended behavior. The operation you are attempting is ambiguous because a month is an ill-defined period of time, as you can see. It often means "The same day in the following month": this is the sense in which Feb 1 is one month after Jan 1 and Mar 1 is one month after Feb 1, despite those being 31 and 28/29 day periods, respectively. It also often means something like, "30 days" or "4 weeks" or "until the next second Monday of the month" or something else. Usually this is entirely encoded in the context.

Relativedelta picks one of these meanings and fixes the semantics, which is why you may be confused if you are implicitly expecting "month" to have a different meaning in your context. Specifically, relativedelta tries to give you "the same day in month m ± n, where m is the month you add it to end n is the number of months". When no such day exists, it falls back to the end of the month.

**Comment by kemar** [comment]
Thank you very much for your answer @pganssle
