### ISSUE TITLE
Adding and subtracting the same relativedelta results in wrong date

### ISSUE THREAD

**Issue by senfbrot** [dateutil/dateutil#1135]
#### Problem

The expression `date(2021, 5, 31) + relativedelta(months=-6) + relativedelta(months=6)` returns `datetime.date(2021, 5, 30)`.

Expected result: `datetime.date(2021, 5, 31)`

#### Minimal example

```python
>>> from dateutil.relativedelta import relativedelta
>>> from datetime import date
>>> date(2021, 5, 31) + relativedelta(months=-5) + relativedelta(months=5)
datetime.date(2021, 5, 31)
>>> date(2021, 5, 31) + relativedelta(months=-6) + relativedelta(months=6)
datetime.date(2021, 5, 30)
>>> date(2021, 5, 31) + relativedelta(months=-7) + relativedelta(months=7)
datetime.date(2021, 5, 31)
```

#### Versions

```sh
❯ python -c 'import dateutil; print(dateutil.__version__)'
2.8.1
❯ python --version
Python 3.7.7
```

**Comment by mariocj89** [comment]
Similar to https://github.com/dateutil/dateutil/issues/1134#issuecomment-847973730.

When you subtract "months" from a date with relative delta you are expecting to get the same day on a previous month.

The first part of your second operation results in the following:
```
>>> date(2021, 5, 31) + relativedelta(months=-6)
datetime.date(2020, 11, 30)   
```
As you are asking for "6 months before the 2021-5-31", the "closest" date to that is "2020-11-30". When you try to add 6 back months to that date, you are getting "2021-5-31".

If you want to add or remove a fixed number of days, you should do that instead by passing "days" rather than months.

Closing as duplicated and working as expected, let me know if you think this still needs some work.
