### ISSUE TITLE
Incorrect datetimes from rrule when using some values as interval 

### ISSUE THREAD

**Issue by giullianopaz** [dateutil/dateutil#1212]
I don't know if this is a BUG with `rrule` or if I'm using it wrong.

I'd like to create Recurrent Time Slots (multiples of 15 minutes). For example, here is a `rrule` working correctly.

```python
>>> start = datetime(2022, 5, 12, 12, 0, tzinfo=UTC)
>>> end = datetime(2022, 5, 15, 18, 0, tzinfo=UTC)
>>> list(rrule(freq=MINUTELY, interval=120, dtstart=start, until=end, byminute=(0, 15, 30, 45), byhour=range(12, 18)))

[datetime.datetime(2022, 5, 12, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 14, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 16, 0, tzinfo=<UTC>),
 
 datetime.datetime(2022, 5, 13, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 14, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 16, 0, tzinfo=<UTC>),
 
 datetime.datetime(2022, 5, 14, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 14, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 16, 0, tzinfo=<UTC>),
 
 datetime.datetime(2022, 5, 15, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 14, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 16, 0, tzinfo=<UTC>)]
```
Everyday slots are the same. They start at 12 PM and end at 4 PM. It works very well for these values as `interval`: `[15, 30, 45, 60, 90, 120, 160]`.

Although, for the values `[75, 105, 135, 150, 165]` it doesn't work as expected.

For example: 
The **expected** behavior for `interval=75`:
```python
>>> start = datetime(2022, 5, 12, 12, 0, tzinfo=UTC)
>>> end = datetime(2022, 5, 15, 18, 0, tzinfo=UTC)
>>> list(rrule(freq=MINUTELY, interval=75, dtstart=start, until=end, byminute=(0, 15, 30, 45), byhour=range(12, 18)))

[datetime.datetime(2022, 5, 12, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 13, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 15, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 17, 0, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 13, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 13, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 15, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 17, 0, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 14, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 13, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 15, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 17, 0, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 15, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 13, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 15, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 17, 0, tzinfo=<UTC>),
```

What the `rrule` is returning **wrongly**:
```python
>>> start = datetime(2022, 5, 12, 12, 0, tzinfo=UTC)
>>> end = datetime(2022, 5, 15, 18, 0, tzinfo=UTC)
>>> list(rrule(freq=MINUTELY, interval=75, dtstart=start, until=end, byminute=(0, 15, 30, 45), byhour=range(12, 18)))

[datetime.datetime(2022, 5, 12, 12, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 13, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 14, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 15, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 12, 17, 0, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 13, 13, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 14, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 15, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 13, 16, 45, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 14, 12, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 14, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 15, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 16, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 14, 17, 45, tzinfo=<UTC>),

 datetime.datetime(2022, 5, 15, 12, 30, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 13, 45, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 15, 0, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 16, 15, tzinfo=<UTC>),
 datetime.datetime(2022, 5, 15, 17, 30, tzinfo=<UTC>)]
```

Why just the first day is right? Why the next days don't follow the rule starting at 12 PM and ending at 5 PM?

**Comment by pganssle** [comment]
> Why just the first day is right? Why the next days don't follow the rule starting at 12 PM and ending at 5 PM?

So the reason for this is that you are indeed misunderstanding the nature of how an RRULE specifies recurrences. The way it works is that you set a specific frequency characterized by `freq * interval`, and the `byxxx` rules serve two functions: if the `xxx` component is **smaller** than the component in `freq`, it *adds additional recurrences*, if it is **larger**, it acts as a *filter*.

So if we look at the unfiltered outcome of your inputs:

```python
>>> print("\n".join(map(datetime.isoformat,
...       rrule(freq=MINUTELY, interval=75, dtstart=datetime(2022, 5, 12, 12), count=22))))
2022-05-12T12:00:00
2022-05-12T13:15:00
2022-05-12T14:30:00
2022-05-12T15:45:00
2022-05-12T17:00:00
2022-05-12T18:15:00
2022-05-12T19:30:00
2022-05-12T20:45:00
2022-05-12T22:00:00
2022-05-12T23:15:00
2022-05-13T00:30:00
2022-05-13T01:45:00
2022-05-13T03:00:00
2022-05-13T04:15:00
2022-05-13T05:30:00
2022-05-13T06:45:00
2022-05-13T08:00:00
2022-05-13T09:15:00
2022-05-13T10:30:00
2022-05-13T11:45:00
2022-05-13T13:00:00
2022-05-13T14:15:00
```

Notice that `2022-05-13T12:00:00` does not appear in the list, because it is 24 hours = 1440 minutes after `dtstart`, and 1440 is not an even multiple of 75. Your version with `interval=120` worked because 120 is an even multiple of 24, and so the frequency lines up nicely with the days.

I'm not entirely sure the best way to express what you want, which is "start at a specific time each day and then give me all the values offset from that time on a specific day". You may need to use an `rruleset`. It can be accomplished easily enough in pure Python:

```python
def recurrences_every_day(date_rrule, day_rrule, count=None, until=None):
    if count is not None and until is not None:
        raise ValueError("Cannot specify both `count` and `until`)

    if count is not None:
       def wrapper(r):
            return itertools.islice(r, 0, count)
    elif until is not None::
        def wrapper(r):
            return itertools.takewhile(functools.partial(operator.ge, until), r)
    else:
        def wrapper(r):
            return r

    for c_date in date_rrule:
        yield wrapper(from day_rrule.replace(dtstart=c_date))
```

Of course, this gives up a lot of the value that `rrule` provides. If the `interval` doesn't need to be completely arbitrary, you may be able to find something that works better, and I haven't spent a lot of time thinking about this, maybe there's a better solution.

My [PyCon US 2019 tutorial](https://ganssle.io/talks/#dealing-with-datetimes-tutorial) has a good section on `rrule`. [The relevant section starts around the 2 hour mark](https://youtu.be/Xt8age1Be4E?t=7188) and is not *too* long (there's an accompanying workbook at the website I linked to). That may help you out in designing your `rrule` or `rruleset`.

As an aside, `rrule` is usually used with "wall time" arithmetic (meetings and such), so I find it interesting that you are using it with UTC. It may be worth considering if it makes sense to actually use UTC or if you want to use "wall time" (e.g. use a naïve time and possibly attach a `zoneinfo.ZoneInfo` to the recurrences). I think there may be a section in the tutorial on wall time vs civil time, towards the beginning (I don't have time now to find it — I definitely cover it at the beginning of my [PyCon US 2019 talk on time zones](https://youtu.be/rz3D8VG_2TY)).

**Comment by giullianopaz** [comment]
So, I was using it wrong. Thank you for the helpful answer.

I'll check the videos and try to solve it in a different way.

Thanks for the `recurrences_every_day` function. It will help a lot too.
