### ISSUE TITLE
Surprising results of parse("12.07.2022") vs parse("13.07.2022")

### ISSUE THREAD

**Issue by mrsalo** [dateutil/dateutil#1224]
Affected dateutil version version: 2.8.2

Using `parse()` on the strings `"12.07.2022"` and `"13.07.2022"` has surprising and inconsistent results: 
```python
In [2]: from dateutil.parser import parse

In [3]: parse("12.07.2022")
Out[3]: datetime.datetime(2022, 12, 7, 0, 0)

In [4]: parse("13.07.2022")
Out[4]: datetime.datetime(2022, 7, 13, 0, 0)
```

**Comment by Lenormju** [comment]
That's because there are many different orderings for date parts. It changes from country to country (cf [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country)).

Using your example format, it could either be interpreted as `day.month.year` or `month.day.year`.  
`13.07.2022` is not ambiguous, it is `day.month.year` (`13 > 12`), but `12.07.2022` is ambiguous and in your case the default was unexpected.  

That's why there is a [`parserinfo` **dayfirst**](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parserinfo) parameter for [`parse()`](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse) :  
> **dayfirst** – Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the day (`True`) or month (`False`). [...]

Code explanation :  
```python
import dateutil
print("version", dateutil.__version__)

from dateutil.parser import parse, parserinfo

for parserinfo, case_name in ((None, "None"),
                              (parserinfo(dayfirst=True), "dayfirst=True"),
                              (parserinfo(dayfirst=False), "dayfirst=False")
                             ):
    print("---")
    print(parse("12.07.2022", parserinfo=parserinfo),
          case_name)
    print(parse("13.07.2022", parserinfo=parserinfo),
          case_name)
```
```
version 2.8.2
---
2022-12-07 00:00:00 None
2022-07-13 00:00:00 None
---
2022-07-12 00:00:00 dayfirst=True
2022-07-13 00:00:00 dayfirst=True
---
2022-12-07 00:00:00 dayfirst=False
2022-07-13 00:00:00 dayfirst=False
```

So if you know that the dates your are parsing are always "dayfirst", then give this info to the parser. You can even simply pass it as a kwarg :  
```python
print(parse("12.07.2022", dayfirst=True))  # 2022-07-12 00:00:00
print(parse("13.07.2022", dayfirst=True))  # 2022-07-13 00:00:00
```

**Comment by mrsalo** [comment]
Thank you very much @Lenormju ,

That makes sense. I was not aware of the `dayfirst=True` option, but it should fix the issue.
