### ISSUE TITLE
Check whether timezone is dateutil.tz instance

### ISSUE THREAD

**Issue by kenahoo** [dateutil/dateutil#1257]
I asked a Stack Overflow question about how to check whether some object is a `dateutil`-style timezone: https://stackoverflow.com/q/75314041/169947 .  My current method is to check `isinstance(tz, dateutil.tz._common._tzinfo)`, but that's using private fields that I probably shouldn't access.

Judging from the plethora of conversation but lack of any answers, there doesn't seem to be an existing way to do this in `dateutil`, could someone point me to it if I've missed it, or if not, could one be added?

### Original question from SO follows:

There are several Python packages that implement the `datetime.tzinfo` interface, including `pytz` and `dateutil`.  If someone hands me a timezone object and wants me to apply it to a datetime, the procedure is different depending on what kind of timezone object it is:

```python
def apply_tz_to_datetime(dt: datetime.datetime, tz: datetime.tzinfo, ambiguous, nonexistent):
    if isinstance(tz, dateutil.tz._common._tzinfo):
        # do dt.replace(tz, fold=...)
    elif isinstance(tz, pytz.tzinfo.BaseTzInfo):
        # do tz.localize(dt, is_dst=...)
    # other cases here
```

(The `dateutil.tz` case is a lot more complicated than I've shown, because there are a lot of cases to consider for non-existent or ambiguous datetimes, but the gist is always to either call `dt.replace(tz, fold=...)` or raise an exception.)

Checking `dateutil.tz._common._tzinfo` seems like a no-no, though, is there a better way?

**Comment by kenahoo** [comment]
Side comment - this whole endeavor really illustrates why the whole `tzinfo` abstraction in Python is broken.  If it's supposed to encapsulate what timezones are, but to use it in practice you have to actually check which concrete class you're dealing with and call different methods based on that information, then that abstraction isn't giving us what we need.

**Comment by pganssle** [comment]
One reason you are having trouble doing this is that it sounds like a bit of an [XY Problem](https://en.wikipedia.org/wiki/XY_problem). You shouldn't need to know what kind of time zone object you have, because they all implement the [`tzinfo` interface](https://docs.python.org/3/library/datetime.html#datetime.tzinfo), and that is more or less the extent of the public interface.

> Side comment - this whole endeavor really illustrates why the whole `tzinfo` abstraction in Python is broken. If it's supposed to encapsulate what timezones are, but to use it in practice you have to actually check which concrete class you're dealing with and call different methods based on that information, then that abstraction isn't giving us what we need.

If the main reason you need to handle this is because `pytz` doesn't use the `tzinfo` interface, then that's not really a problem with the `tzinfo` interface, except insofar as — in its original, pre-PEP 495 incarnation — it induced `pytz` to create its interface.  If that is the extent of the problem, then you don't need to detect `dateutil` time zones, you just need to detect `pytz` time zones, since everything else implements the `tzinfo` interface.

If you have some new library, one thing to do here would be to simply not support pytz. Another option would be to use [`pytz-deprecation-shim`](https://pypi.org/project/pytz-deprecation-shim/), or to re-implement [some of the helper functions](https://pytz-deprecation-shim.readthedocs.io/en/latest/helpers.html) to help you detect `pytz` zones. `pytz-deprecation-shim` is designed for exposing an interface that doesn't break people relying on `pytz` attributes, but also works properly with the `tzinfo` interface. You should probably not expose that interface directly to consumers, and instead do something like [`upgrade_tzinfo`](https://pytz-deprecation-shim.readthedocs.io/en/latest/helpers.html#pytz_deprecation_shim.helpers.upgrade_tzinfo), to automatically upgrade `pytz` zones to their modern equivalents.

**Comment by kenahoo** [comment]
Thanks for the reply.  I don't think I have an XY problem, though.

> You shouldn't need to know what kind of time zone object you have, because they all implement the [tzinfo interface](https://docs.python.org/3/library/datetime.html#datetime.tzinfo), and that is more or less the extent of the public interface.

Unfortunately, I've found the `tzinfo` insufficient to perform even simple tasks, like "given a tz-naive datetime `d` and a timezone `tz`, apply `tz` to `d`" with consistent semantics across `tzinfo` implementations.

There are so many "wrong" (things that seem like they should do one thing, but actually do another - or just differences from one library to another) ways to do this, depending on the specific classes being used[^1][^2], that I started writing a function `with_tz` (inspired by R's [function of the same name](https://lubridate.tidyverse.org/reference/with_tz.html)) that provides the correct invocation for the desired semantics (apply the timezone, with consistent and controllable behavior at DST boundaries).

There are other helpers in the library too, for example for doing datetime arithmetic properly.

The "fastest footgun" article is good, I've seen it, it's indeed one reason I'm switching our actual application code away from its previous "just use `pytz`" approach and trying to help people migrate to alternatives.

I'm curious - is there some reason you *don't* want to let people query whether an object is a `dateutil`-based timezone?  That's not usually off-limits for a library.

[^1]:  `d` might be a `datetime.datetime` scalar, or `pandas.Timestamp` scalar, or `pandas.DatetimeIndex` vector, or `pandas.Series[object]` vector containing `datetime.datetime` objects, or `numpy.datetime64` vector.
[^2]: `tz` might be a string, or `pytz` object, or `dateutil` object, or `zoneinfo` object if Python is v3.9+, or `pendulum` object.

**Comment by pganssle** [comment]
> Unfortunately, I've found the `tzinfo` insufficient to perform even simple tasks, like "given a tz-naive datetime `d` and a timezone `tz`, apply `tz` to `d`" with consistent semantics across `tzinfo` implementations.

This again sounds like you need to know if the time zone is `pytz`, not if it's a `dateutil` zone, since you can accomplish this with:

```
if is_pytz(tz):
    warnings.warn("Stop using pytz please!")
    return tz.localize(d)
else:
    return d.replace(tzinfo=d)
```

As I said before, you don't need to know what kind of `tzinfo` you have as long as you know it's not `pytz`.

If you are migrating away from `pytz`, you can use `pytz-deprecation-shim`, and then wrap all time zones coming in with the shims and treat them like they aren't `pytz` zones.



> I'm curious - is there some reason you _don't_ want to let people query whether an object is a `dateutil`-based timezone? That's not usually off-limits for a library.

Yes, because if we expose this detail, people will start relying on it. It's not good for us (prevents us from making changes like starting to return non-`dateutil.tz` zones from `tz.gettz()`), and it's not good for the ecosystem, since there will be a bunch of code out there that says, "If this is a dateutil zone, do X" instead of using the `tzinfo` interface, which allows for the use of any compatible zone object.

**Comment by kenahoo** [comment]
> As I said before, you don't need to know what kind of `tzinfo` you have as long as you know it's not `pytz`.

That might be true if I can consider things like `dateutil.tz.datetime_ambiguous()` and friends "part of the `tzinfo` interface", is that the intention?  Or are they only supposed to work with timezones of the `dateutil` flavor?  It seems to have custom stuff like "check whether a time zone defines its own `is_ambiguous` function", which AFAIK isn't part of the `tzinfo` interface.

**Comment by pganssle** [comment]
`datetime_exists `, `datetime_ambiguous` and `resolve_ambiguous` work with all standard time zone providers. They may work with `pytz`, I'm not sure.

**Comment by pganssle** [comment]
I think there's no compelling reason here to add support for this, so I'm going to close the issue. We can always re-open it if someone presents a compelling reason.
