### ISSUE TITLE
ParserError is in a private submodule

### ISSUE THREAD

**Issue by lhupfeldt** [dateutil/dateutil#1264]
`parser("A")`

raises

`dateutil.parser._parser.ParserError`

I want to catch the exception.
The exception should not be in a private  module, it is propagated to client code.

**Comment by pganssle** [comment]
I believe it's an implementation detail that it originates in a private module. It's exposed directly in the `parser` module as well: https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.ParserError

**Comment by lhupfeldt** [comment]
At least I will not have to import a private module then.
I still think it is bad raise the exception from a private module, it causes the implementation details to be exposed to users.
It would be more appropriate to define the exception in `dateutil.parser` and raise that. This could be made backwards compatible (in case anynody catch the private exception).

**Comment by pganssle** [comment]
> I still think it is bad to raise the exception from a private module, it causes the implementation details to be exposed to users.
> It would be more appropriate to define the exception in `dateutil.parser` and raise that.

The reason it's defined in the private module is that the parser itself is implemented in a private module. It would create a dependency cycle if `ParserError` were defined in `dateutil.parser`, because `dateutil.parser` depends on `dateutil.parser._parser` to get the parsing functions, but `dateutil.parser._parser` would need to depend on `dateutil.parser` in order to import `ParserError` in your suggestion.

> This could be made backwards compatible (in case anybody catch the private exception).

For the record, I do not care about this. The fact that it's in a private module means don't rely on it.

We might be able to modify the class's `repr` or something. I'm not entirely sure how easy it would be.

**Comment by lhupfeldt** [comment]
None of the solutions seem really appealing

1. As you said, change repr
2. Move the ParserErro class to __init__.py, make a small wrapper and down the Exception class defined there to the private function.
3. Do late import to avoid the circular import

Maybe too many workarounds for a minor thing.

It may be better to move the exception class to a third module in the next major release.
