### ISSUE TITLE
timezone info not used when inbetween

### ISSUE THREAD

**Issue by sebix** [dateutil/dateutil#189]
I encountered this format `Tue Feb 23 00:44:27 PST 2016` [here](http://security-research.dyndns.org/pub/botnet/ponmocup/ponmocup-finder/ponmocup-infected-domains-latest.txt) which is parsed correctly, except for the important timezone info:
```python
>>> dateutil.parser.parse('Tue Feb 23 00:44:27 PST 2016')
datetime.datetime(2016, 2, 23, 0, 44, 27)
```
PST is -08:00!

**Comment by pganssle** [comment]
Hm.. I suspect that this is because it doesn't have a good way of knowing what the time zone is just from an abbreviation like 'PST', which is context-specific. I'll look into the degree to which this can be improved, but I don't know that it'll ever be flawless.

It seems like this is the expected behavior, based on [this test](https://github.com/dateutil/dateutil/blob/master/dateutil/test/test.py#L5356).

For now, the right thing to do is to use the `tzinfos` parameters (see [this example](https://dateutil.readthedocs.org/en/latest/examples.html#parse-examples)):

```python
>>> from dateutil import tz
>>> from dateutil.parser import parse
>>> TZOFFSETS = {'PST': tz.gettz('America/Los_Angeles')}
>>> parse('Tue Feb 23 00:44:27 PST 2016', tzinfos=TZOFFSETS)
datetime.datetime(2016, 2, 23, 0, 44, 27, tzinfo=tzfile('/usr/share/zoneinfo/America/Los_Angeles'))
```

**Comment by sebix** [comment]
> Hm.. I suspect that this is because it doesn't have a good way of knowing what the time zone is just from an abbreviation like 'PST', which is context-specific.

PST is always -08:00, nothing context-specific here.

> It seems like this is the expected behavior, based on this test.

`ignoretz` is set to `True`, so I'd say no.

UTC, GMT and probably others are always detected, no matter where they are, so it's not about the position but about PST.
```python
>>> parse("12:00 PST")
datetime.datetime(2016, 2, 23, 12, 0)
>>> parse("12:00 GMT")
datetime.datetime(2016, 2, 23, 12, 0, tzinfo=tzutc())
>>> parse('Tue Feb 23 00:44:27 UTC 2016')
datetime.datetime(2016, 2, 23, 0, 44, 27, tzinfo=tzutc())
>>> parse('Tue Feb 23 00:44:27 PST 2016')
datetime.datetime(2016, 2, 23, 0, 44, 27)
```
Doesn't have dateutil a list of tz abbreviations built-in? Otherwise one has to always give a mapping at each call.

**Comment by pganssle** [comment]
@sebix UTC and GMT are detected because they evaluate to `tzutc`, it's a different code path. Similarly, if your computer is actually *in* PST, it will end up evaluating to `tzlocal()`, because it will be detected as being the time zone abbreviation stored by your OS (on Linux, anyway).

The problem is that the three-letter time zones are not guaranteed to be unique and are not the canonical lookup values for specific time zones. Consider 'CST', which could be "Central Standard Time", "Cuba Standard Time" or "China Standard Time".

I do not foresee hard-coding PST into dateutil even though it currently only resolves to UTC-8.
