### ISSUE TITLE
_isdst() returns different values..

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#196]
...depending on if its a `tz` or `tzwin` object
```python
from datetime import datetime
from dateutil import tz

now = datetime.now()

tzl = tz.tzlocal()
tzwl = tz.tzwinlocal()

print(tzl._isdst(now), tzwl._isdst(now))
# 0 False
```
Now granted those are protected methods, but you would assume that those would return the same types of values.

**Comment by pganssle** [comment]
Agreed. Not critical but I'll look into it.

**Comment by pganssle** [comment]
There doesn't seem to be much consistency between `_isdst` methods, some of them return boolean values, others return integer values. Since it's not public-facing and there are no performance concerns involved in an inconsistent internal type, I don't see any reason to add the (minimal) overhead of converting it to bool before it's necessary.
