### ISSUE TITLE
Garbage input for parse returns a datetime, not an TypeError

### ISSUE THREAD

**Issue by tpievila** [dateutil/dateutil#21]
A user reported a bug:

When "a" is provided as input str to the parser, TypeError exception is
expected. Instead, the parser returns a datetime object.

    >>> import dateutil.parser as d_parser
    >>> d_parser.parse*('a')*
    datetime.datetime(2014, 11, 10, 0, 0)

**Comment by pganssle** [comment]
I'm nearly 100% sure this shouldn't throw a `TypeError`, if anything it should throw a `ValueError`, since parsers are supposed to parse strings, and this is just a malformed string. That said, the reason this is happening is because `a` is interpreted as "AM", and "AM" is basically ignored when parsing the hours unless the hour specified is 12 (because 12am = 0:00 in 24-hour time). Since an empty string `d_parser.parse('')` returns midnight of the current day, the string `'a'` is treated like `''` with any specified numbers treated as AM.

You'll note that `d_parser.parse('p')` actually *does* throw an error, but not deliberately, it's just thrown because the hour is specified as `None` and it tries to add 12 to the hour. This doesn't seem like a high priority bug, but probably both of these issues can be fixed easily by throwing a `ValueError` any time AM or PM is specified without an hour being specified, since that's a non-sensical situation.

Another issue is that the parser is not checking for non-sensical inputs such as `dparser.parse('14am')`, which is parsed as 2 PM. Again, this is non-sensical because AM and PM are specifiers for a 12-hour clock, so all numbers should be in the range `1 <= hour <= 12`.

Either way, the parser should be explicit about how these edge cases are handled in the documentation. I can prepare a PR for these changes.
