### ISSUE TITLE
`parse('now', fuzzy=True)` broken in 2.5

### ISSUE THREAD

**Issue by ProgVal** [dateutil/dateutil#212]
2.4:

```py
>>> import dateutil, dateutil.parser
>>> dateutil.__version__
'2.4.2'
>>> dateutil.parser.parse('now', fuzzy=True)
datetime.datetime(2016, 3, 8, 0, 0)
```

2.5:

```py
>>> import dateutil, dateutil.parser
>>> dateutil.__version__
'2.5.0'
>>> dateutil.parser.parse('now', fuzzy=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/progval/.local/lib/python3.4/site-packages/dateutil/parser.py", line 1161, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/progval/.local/lib/python3.4/site-packages/dateutil/parser.py", line 555, in parse
    raise ValueError("String does not contain a date.")
ValueError: String does not contain a date.
```

**Comment by pganssle** [comment]
@ProgVal What you were doing before was definitely a hack. Consider 2.4.2's behavior for other similar strings:

```python
>>> from dateutil import parser
>>> parser.parse('now', fuzzy=True)
datetime.datetime(2016, 3, 8, 0, 0)
>>> parser.parse('tomorrow', fuzzy=True)
datetime.datetime(2016, 3, 8, 0, 0)
```

I suspect that you may have been fooled because the default behavior if a string contains a date used to be to return the "default" date, which defaults to, "today" (notice how `'now'` didn't even return the current time?).

If you want to keep the old behavior, just wrap it in a try-catch block:
```python
from dateutil import parser
import datetime

try:
    dt = parser.parse('now', fuzzy=True)
except ValueError as e:
    dt = datetime.datetime.now()
```

In the 2.6.0 release, I'm planning on switching the errors over from `ValueError` to custom error classes so they can be more easily differentiated in error flow, but for now you can parse the message if you need to distinguish between causes of the errors.

**Comment by ProgVal** [comment]
I see. Thanks for the detailed answer.
