### ISSUE TITLE
Error when creating datetime.time with dateutil.tz.tzwinlocal

### ISSUE THREAD

**Issue by labrys** [dateutil/dateutil#216]
While testing #59 I found a related issue when using `tzwinlocal()`
```python
>>> import datetime
>>> from dateutil import tz
>>> t1 = datetime.time(1, 2, tzinfo=tz.tzutc())
>>> t2 = datetime.time(1, 2, tzinfo=tz.tzlocal())
>>> t3 = datetime.time(1, 2, tzinfo=tz.tzwinlocal())
>>> print(t1)
01:02:00+00:00
>>> print(t2)
01:02:00
>>> print(t3)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    print(t3)
  File "C:\Python35\lib\site-packages\dateutil\tz\win.py", line 135, in utcoffset
    if self._isdst(dt):
  File "C:\Python35\lib\site-packages\dateutil\tz\win.py", line 172, in _isdst
    dston = picknthweekday(dt.year, self._dstmonth, self._dstdayofweek,
AttributeError: 'NoneType' object has no attribute 'year'
>>> 
```
This was tested on Windows 10 using Python 2.7.11 and 3.5.1

**Comment by pganssle** [comment]
@labrys Seems to be working fine for me on 2.7 and 3.4:

```python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil
>>> print(dateutil.__version__)
2.5.0
>>> from dateutil import tz
>>> import datetime
>>> print(datetime.time(1, 2, tzinfo=tz.tzwinlocal()))
01:02:00+02:00
```

**Comment by pganssle** [comment]
Oh, my bad, I had set the time zone in the VM to be Harare, Praetoria - they don't have any DST.

Bug is confirmed.

**Comment by pganssle** [comment]
Hm... it occurs to me that this could be problematic if I make it consistent with the behavior from #132.

For zones with no DST, `utcoffset` and `dst` can definitely be returned. For zones with DST, it seems like it should return `None`, because the DST, UTC offset and tzname are not well-defined.

For now, I'm going to have non-DST zones continue returning the the standard time value, and DST zones return `None`.
