### ISSUE TITLE
Latest version of dateutil fails on GAE (google app engine)

### ISSUE THREAD

**Issue by savraj** [dateutil/dateutil#239]
Problem: dateutil is not working on Google App Engine.  

The file `/dateutil/zoneinfo/__init__py` contains the line `from subprocess import check_call` which isn't permitted on App Engine.  

Fortunately this does not appear to be used anywhere in the file, and all the tests pass, when you simply remove this line.   A closed issue does reference this same problem -- Issue #97 -- and I think removal of this line was overlooked when the actual calls of `check_call` were migrated to rebuild.py.

I may not be testing correctly so it would be nice for someone else to verify this.  I can also provide a super minimal appengine project that reproduces the issue.

Dateutil is a wonderful and super useful library. Thanks for making it great and I look forward to your feedback here!

**Comment by pganssle** [comment]
I agree with your assessment. If you want to make a pull request, please branch off the `2.5.x` branch, not the `master` branch, as I'll include this in 2.5.3. Otherwise it's a simple matter for me to do it.

As an aside, doesn't Google App Engine provide a zonefile? Is this coming up in an actual app, or is this just causing test failures on GAE? Generally you don't need to import `zoneinfo` except on systems that don't have a tzdata file (though if you call `gettz()` with a bad time zone name, it _will_ induce the `tz` module to attempt a `zonefile` import).

**Comment by savraj** [comment]
Nice, thanks! I'll create the pull request.  So this came up in an actual app -- after I imported the [arrow](https://github.com/crsmithdev/arrow) library (which depends on dateutil) and called `arrow.now('US/Eastern')` (or made any other tz-related call).  As far as I know App Engine does not include a zonefile, another way to get a zone file is [pytz.gae](https://github.com/brianmhunt/pytz-appengine).  Thanks for your prompt response!

**Comment by pganssle** [comment]
@savraj Ah, that's interesting. Usually *nix-like systems have a zonefile already. I'm very surprised that this hasn't caused more issues for people if they aren't providing a zonefile.

**Comment by pganssle** [comment]
Fixed by #240.
