### ISSUE TITLE
rule._byweekday as set broke backward compatibility

### ISSUE THREAD

**Issue by pypingou** [dateutil/dateutil#24]
`rule._byweekday` used to be a list and moving it to a set broke backward compatibility.

For example, vobject no longer works with the most recent dateutil, backtrace available at:
http://jenkins.cloud.fedoraproject.org/job/fedocal/456/console

**Comment by ralphbean** [comment]
Attributes that begin with a ``_`` are generally considered "private" and not part of a public API.  So I wouldn't call it a break in backwards compatibility and instead call it a bug in that vobject library.

**Comment by pganssle** [comment]
I agree with @ralphbean. vObject shouldn't be directly accessing private variables like that.

@pypingou Is there no way to do what vObject is trying to do using the publicly exposed methods and functions? If not, maybe the solution is to add a public interface to some of these internal variables so that your use case is officially supported.

**Comment by pypingou** [comment]
Thanks for your feedbacks, I think that in fact the much larger problem is the fact that vobject is pretty much dead upstream with no real project providing the same functionality (icalendar isn't complete iirc).

I will look if I can do something on the vobject side, which I think is the better long-term solution.

**Comment by jarondl** [comment]
Well put @pganssle. 
I am closing as wontfix.

relvant link: http://xkcd.com/1172/
