### ISSUE TITLE
ValueError: month must be in 1..12� - parser.parse module

### ISSUE THREAD

**Issue by Wu4m4n** [dateutil/dateutil#242]
Hi,
Just a little report.

I have this code.
with the version python-dateutil 2.5.2
```
import datetil.parser
dateString = '2016-03-21'
date = dateutil.parser.parse(dateString, dayfirst=True)
print date
```
And show the next error.

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    date = dateutil.parser.parse(dateString, dayfirst=True)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 577, in parse
    ret = default.replace(**repl)
ValueError: month must be in 1..12

```

But if I install the version 2.2

Works perfect!

PD: I use pip to install python-dateutil.

**Comment by pganssle** [comment]
Duplicate of #233, fixed in #234.

**Comment by Wu4m4n** [comment]
Thanks pganssle !

**Comment by Wuyanan520** [comment]
i meet the same problem when i do  dateutil.parser.parse('201508'),what should i do?

**Comment by Wu4m4n** [comment]
you forgot to write the day. 2015 = year , 08, month , and the days?

**Comment by pganssle** [comment]
@Wuyanan520 That is, evidently, a separate bug, as I am able to reproduce it, you can report as a separate issue.

That said, I think the "correct" behavior would be to parse `201508` as YYDDMM, because the way the parser works if it sees a 6 digit string and it doesn't already have a year/day/month, it will figure that's what it's dealing with, so the logic will go like this (for unspecified `dayfirst`):

1. Break up the string into 20, 15, 08
2. Check to see if it's MMDDYY -> 20 is too big to be a month, so eliminate that choice.
3. Check to see if it's YYMMDD -> 15 is too big to be a month, so eliminate that choice.
4. Check to see if it's YYDDMM -> 15 can be a day and 08 can be a month, so confirmed.

If `201508` is intended to represent August 2015, then, if possible, you should change the format to "2015-08" or "2015.08" or "2015/08" or something like that, or special case these 6-digit dates yourself.

Additionally, I'll note that if you know that all your dates are of the format `YYYYMM` (or just in general you know the exact format of the dates), then you probably shouldn't be bothering with `dateutil.parser` at all. You can just do this: `dt = datetime.strptime('201508', '%Y%m')`. Of course, this will resolve to `2015-08-01`, while dateutil's parser (probably unexpectedly) returns missing values from *today*'s date unless specified. In case that's a behavior you want, you can probably just do `dt.replace(day=datetime.today().day())`.
