### ISSUE TITLE
parse iso format with option dayfirst

### ISSUE THREAD

**Issue by glaucouri** [dateutil/dateutil#268]
It would seem to be an issue related to dayfirst options in ISOFORMAT date.
This is an unambiguous date, so i expect does not come into play the "dayfirst" option.

**Version 2.4.2**

In [1]: parser.parse('1995-02-03')
Out[1]: datetime.datetime(1995, 2, 3, 0, 0)

In [2]: parser.parse('1995-02-03', dayfirst=True)
Out[2]: datetime.datetime(1995, 2, 3, 0, 0)

**Version 2.5.3**

In [1]: parser.parse('1995-02-03')
Out[1]: datetime.datetime(1995, 2, 3, 0, 0)

In [2]: parser.parse('1995-02-03', dayfirst=True)
Out[2]: datetime.datetime(1995, 3, 2, 0, 0)

Thanks in advance
Glauco

**Comment by pganssle** [comment]
The date you specified _is_ an ambiguous date, considering that the parser is able to generate two valid dates from it. For more on the behavior of `dayfirst`, see #238, where I give a thorough explanation.

**Comment by glaucouri** [comment]
Why is ambiguous? this is the ISO standard. 

This is the standard used in many DBMS, Pandas, sqlalchemy, 
this ambiguity was inserted in the 2.5.* ranch, never before i've noticed 
ambiguity whis iso8601

take a look:
https://en.wikipedia.org/wiki/ISO_8601

Thank you
Glauco

**Comment by pganssle** [comment]
@glaucouri It is ambiguous because there are two possible values that it can refer to. The concept of the parser is that it parses dates for which you don't know the format. If you know that the format is an ISO-8601 date, use `strptime` instead.

In any case, just don't specify `dayfirst` if you don't want the day to be given priority over the month when there are two possible interpretations.

**Comment by kovidgoyal** [comment]
This is a regression. Now dateutil.parser cannot be used to parse unknown format date strings on a system in accordance with the system locale. In order to parse the date 01-02-2012 correctly according to the system locale, one has to pass the day_first option. If the day_first option is passed, then if the datestring being parsed is an ISO format date, it will be parsed incorrectly.

So now parse() can either parse 01-02-2012 correctly or parse ISO 8601 dates correctly, not both. And this was not the case before 2.5.x

I can workaround this fairly easily in my code by simply detecting dates that match `^\d{4}-\d{2}-\d{2}` and not passing dayfirst in that case. But the fact remains that is a backwards incompatible change that breaks working code.

**Comment by pganssle** [comment]
@kovidgoyal I'm not sure the original intention of the parser was to fall back to parsing ISO dates if the `dayfirst` option was not specified - I think that was an unintended consequence. I agree, however, that there's certainly an identifiable need to be able to provide some interface which allows downstream users to handle fallback ordering as desired.

As I've mentioned on other issues (such as #125 and #214, among others), I think the way forward is to do two things:

1.  Provide an output format that can be re-used to parse strings of the same type, with a public interface for querying the string ordering in some identifiable way (this way you can parse, determine if the string was parsed in a way you didn't expect, then parse again with different options if need be). I think this is useful in general (so you can, for example, "cache" the parse operation), but not the most efficient way to handle the problem.

2.   Provide a public interface for tweaking the preference ordering for ambiguous dates. I'm definitely looking for suggestions on how this should look, but I'm thinking that it will start with a refactor of `parser.parser` to break out the monolithic `parse` function into small, modular functions (which can be individually adjusted in subclasses), and also to move things like ambiguity resolution of individual tokens into some instance and/or class parameters, like, `date_tokens = ['mdy', 'myd', 'dmy', 'ymd']`, or even some variation on `strftime` syntax like `%Y%^%m%^%d` where `%^` would be a generic substitute for "any separator".

I do not think that a fundamental parser overhaul will be in the 2.6.0 release (the time zone improvements so far are significant and once they are done I see no reason to delay a major release for as long as it would take to decide on an interface and then implement it. My current plan is to finish the 2.6.0 release, then start on the parser modularization, then I'll open an issue requesting comments on the implementation details of how to specify fallback options.

**Comment by kovidgoyal** [comment]
Regardless of whether it was the original intention or not, it was the actual behavior. Changing it silently is not nice -- it creates hard to debug errors in downstream projects. Certainly such a change should not happen in a minor release, since it is backwards incompatible. 

Anyway, that is water under the bridge. Coming to the question of how the parser should behave. To me, the intuitive behavior is:

1) Detect if the string is in a well known format, such as ISO 8601, RFC 2616 etc. and parse according to that format, if so. Obviously, this cannot be made 100% bulletproof, but I think it can be made robust enough for most practical purposes.

2) Detect if the date is unambiguous and parse accordingly, if so. Note that I would consider ^\d{4]-\d{2}-\d{2} to be unambiguous, since, while it is technically possible for it to be either YYYY-MM-DD or YYYY-DD-MM I have never actually come across the latter format anywhere. If you dont want it to be unambiguous, then there needs to be an option to get the parser to treat it as such.

3) Allow the user to specify YMD ordering for ambiguous dates, defaulting to the system locale. If you want, I can contribute code for getting the system locale ordering on all major OSes

From my perspective, the ideal interface for parser would be

```py
def parse(string, ymd_order=None, yyyy_xx_xx_ambiguous=False, ampm_time=None):
   # where ymd_order=None means use system locale, other possible values are permutations of 'ymd'
   # where ampm_time=None means use system locale for interpreting ambiguous hour values. True means assume ambiguous values are in 12hr format, False means assume they are in 24 hr format.
```

I suggest keeping the interface of parse as simple as possible and having a Parser class that can be customized more deeply for people that need different behaviors.

Of course, these are just my preferences -- I offer them to you for consideration in your final design.

**Comment by kovidgoyal** [comment]
Some evidence for my claim that YYYY-XX-XX should be unambiguous:
http://stackoverflow.com/questions/2254014/are-there-locales-or-common-programs-that-use-yyyy-dd-mm-as-the-date-format

**Comment by labrys** [comment]
Kazakhstan uses YYYY-DD-MM

**Comment by kovidgoyal** [comment]
Exactly, according to https://en.wikipedia.org/wiki/Date_format_by_country there is no country in the world that uses YYYY-DD-MM with hyphen or slash separators. That is probably why the hyphen was chosen for ISO 8601 in the first place. In fact, I think that one could make the following regex unambiguous

^\d{4}[/-]\d{1,2}[/-]\d{1,2}

**Comment by pganssle** [comment]
Not that it matters really, as it doesn't really impact the final outcome, but the parser doesn't really keep track of what the separators are. It doesn't work by trying a bunch of different date formats, it tokenizes the strings and infers what the parts of a datetime format are. `YYYY.DD.MM` vs `YYYY-DD-MM` are more or less equivalent to the parser.

Honestly, if you have some ISO dates and some dates of an unknown format, you may want to just try parsing it with `strptime` with an ISO format first, then if it errors, run the parser on it.

**Comment by kovidgoyal** [comment]
Dont worry about it, I've already taken care of my use case, and also removed dateutil from the code paths most likely to encounter 8601 dates. Gives a nice performance boost (parsing 8601 dates is now ~50x faster) as well :)

So I dont really have a dog in this race any more. IMO, the behavior I described above is intuitive, but, this is your project, I have no way of knowing all the constraints/goals it is trying to optimize for.

My only remaining request is please dont break backwards compatibility in minor releases.

**Comment by pganssle** [comment]
Obviously we didn't intend to break backwards compatibility, but it's hard to define exactly what "backwards compatibility" means in general. If you look at where that change came from, I figured it was a bug that "dayfirst" worked in some cases and not in others. I'll admit that, in retrospect, a surprising amount of people were relying on this particular behavior, but to some extent all bugfixes change behavior in a "backwards-incomptible" way for people relying on bugfixes.

As for speed, I'm glad it worked out that way. I don't think most people realize that, under the hood, the parser is quite slow because it has to do a lot of work inferring date formats - which is why we always recommend that you use `strptime` if you _know_ the format of the string. Hopefully we can speed things up somewhat in the 2.7.0 release by providing the ability for people to "cache" the date-inference portion of it, since most of the time if you have a big list of dates, most of them will be in the same format (or in a small number of formats) - no need to do all that work every time.

**Comment by kovidgoyal** [comment]
It is indeed hard to avoid accidentally breaking things in any project of reasonable complexity, but, when you do discover you have broken things unintentionally, you really should roll back the change and shelve it for a major release, if at all possible. Knowing that a library tends to break things in minor releases does not do wonders for my confidence in relying on it. 

The speed difference is indeed very large (incidentally, I did not use strptime but wrote a dedicated 8601 parser in C).  You could perhaps add a note to the documentation of parse() saying that it should not be used for dates in known formats, and perhaps provide strptime expressions for a couple of common formats. That will help your users do the right thing, and also make changes to the parser that break things affect less people. I suspect that many people are lazy and just use dateutil to parse known format dates because there is no easy out of the box solution for the common formats (you have to hunt around to find dedicated modules for each format).

**Comment by kovidgoyal** [comment]
Also, personally, I would find a small note outlining the algorithm/assumptions that parse makes to be helpful, somewhere in its documentation. That way, future people like me will be less likely to assume parse() works in a way it does not.

**Comment by nshgraph** [comment]
As we have just encountered this same issue and will now be reverting the version to 2.5.1 

I'd be very interested in the rationale behind using the terminology 'dayfirst' rather than 'ordered'. I am not an expert on date formats (I just have to deal with huge variations in csv files). But it seems there is either 'ascending/descending' locales (YMD / DMY) and 'inverted' (YDM / MDY). This seems more logical (to me) than dayfirst as I only know the originating locale and not whether they decided to put the year first or last.

**Comment by qpkorr** [comment]
+1 for seeing the attempted bugfix as a breaking change.  In Australia, our standard formats would be either DDMMYYYY or YYYYMMDD (ISO format) - and dateutil used to read those both correctly with dayfirst set to true and yearfirst not explicitly set.  According to the table in issue #238, there's now no way to configure this behaviour.  We're trying to move from debian jessie to stretch - I guess we'll just pin stretch to the jessie version of dateutil, until you have time to provide an interface that allows these preferences to be specified. Thanks for all your hard work!

**Comment by NinjaMeTimbers** [comment]
As someone living in Canada, our standard date formats are YYYYMMDD and DDMMYYYY like the commenter above in Australia. I need a way to preferentially use YYYYMMDD then DDMMYYYY which worked fine in version 2.5.1 using dayfirst=True.  Reading the documentation it seems to support my interpretation of how dayfirst should work:

> dayfirst – Whether to interpret the first value in an ambiguous 3-integer date (e.g. 01/05/09) as the day (True) or month (False). If yearfirst is set to True, this distinguishes between YDM and YMD. If set to None, this value is retrieved from the current parserinfo object (which itself defaults to False).

According to my reading of this, if dayfirst=True and yearfirst=False, it should only be concerned with the first value of a 3-integer date so it should still interpret 2020-01-05 as 2020-January-05 based on the documentation, however it actually interprets it as 2020-May-01. According to the documentation it should only be interpreting it as YYYYDDMM if yearfirst=True.

**Comment by mcarans** [comment]
YYYYMMDD and DDMMYYYY parsing is what is needed for anywhere outside the US!

**Comment by qpkorr** [comment]
Since writing my previous comment lamenting the "fix" that this thread addresses, some time ago I added the following comment to my code for when we upgrade past dateutil version 2.5.1. Sharing it just in case it assists anyone else.

# We've had some issues with upgrading to dateutil version 2.5.3 (in debian stretch) as it's incapable
# of easily handling both iso formats, and dd/mm/yyyy formats.
# Version 2.7(.3 - in buster) adds a new function, dateutil.parser.isoparse
# for parsing iso formats only.  So - when we move to this, we should simply
# try parsing a date with dateutil.parser.isoparser, and if that gives an exception
# (as it will for "1/2/1999"), try again with dateutil.parser.parse(obj, dayfirst=True, ...)
# Hopefully this will retain the flexibility we had in version 2.5.1, terms of correctly interpretting
# 2019-02-01 and 1/2/2019 as the same date.

I've not tested this much - but I'm hopeful it will work for us at least.
