### ISSUE TITLE
IST (India Standard Time) is not parsed

### ISSUE THREAD

**Issue by lawre** [dateutil/dateutil#273]
I'm on dateutil version 2.5.3.

IST is not recognized as a timezone.

CST works fine:
```
>>> import dateutil.parser
>>> dateutil.parser.parse("Sun May  8 03:10:20 CST 2016")
datetime.datetime(2016, 5, 8, 3, 10, 20, tzinfo=tzlocal())
```

IST doesn't parse
```
>>> dateutil.parser.parse("Sun May  8 03:10:20 IST 2016")
datetime.datetime(2016, 5, 8, 3, 10, 20)
```

I poked around in the dateutil-zoneinfo file and did not see an IST file anywhere.

**Comment by pganssle** [comment]
@lawre You are able to parse `CST` likely because your local machine's time zone is Central, and the local time zone abbreviations are in the parser's search path. Generally, 3-letter time zones other than UTC and GMT are not supported because they are by nature ambiguous (CST, for example is overloaded - Cuba Standard Time, Central Standard Time, China Standard Time, etc).

If you want to parse IST correctly, you should construct a `tzinfo` object and pass it to the `tzinfos` parameter of the parser:

```
>>> from dateutil import tz
>>> from dateutil.parser import parse
>>> IST = gettz('Asia/Kolkata')
>>> tzinfos = {'IST': IST}
>>> parse("Sun May  8 03:10:20 IST 2016", tzinfos=tzinfos)
datetime.datetime(2016, 5, 8, 3, 10, 20, tzinfo=tzfile('/usr/share/zoneinfo/Asia/Kolkata'))
```

When #227 is merged (which will be before the next release), you will be able to avoid using `tzinfos` for things that show are in the Olson database (which are unambiguous time zones), but that will not (and likely will never) include three-letter abbreviations - you'll have to disambiguate them yourself given your specific context.

**Comment by lawre** [comment]
thank you for the feedback and tip.
