### ISSUE TITLE
Allow comma as a separator between seconds and microseconds

### ISSUE THREAD

**Issue by b4stien** [dateutil/dateutil#28]
According to http://en.wikipedia.org/wiki/ISO_8601#Times (relevant quote: http://en.wikipedia.org/wiki/ISO_8601#cite_note-15) the preferred decimal sign should be a comma (although a dot is also valid).

Currently a comma is not recognised (but a dot is).

````
>>> parse("2015-02-05T13:34:04,000+0000")
[...]
ValueError: unknown string format

>>> parse("2015-02-05T13:34:04.000+0000")
datetime.datetime(2015, 2, 5, 13, 34, 4, tzinfo=tzutc())
```

**Comment by pganssle** [comment]
This should probably be addressed while fixing (or otherwise making consistent) Issue #19.

**Comment by b4stien** [comment]
Is there something I can do to help? Do you want me to write some tests?

**Comment by pganssle** [comment]
@b4stien I don't think the tests will be a big problem, they're usually pretty easy to write once the code is there. If you'd like to try tackling this problem, I've tried recently to improve the documentation of the algorithm, so hopefully it's getting easier to understand from reading the code.

The way the parser currently interprets things is quite complicated, and there can be various collisions in interpretation, so be careful what you change. There's probably a way to simply add commas as decimal points, but at the moment dots are treated differently than other separators because they may be *part of a number*, not just a separator. I worry that by allowing commas as decimal points, there could be similar interpretation collisions. These issues have to be dealt with to resolve Issue #19 anyway, and it's possible that the best way to fix things would be to overhaul the way the parser tokenizes and processes the strings rather than to add in comma support on top of the existing framework.

**Comment by b4stien** [comment]
So I tried for a while, and thanks for your insights, but I'm afraid I didn't end up with something satisfying...

**Comment by pganssle** [comment]
@b4stien Yes, one of the biggest problems is that what formats are and are not supported is not actually documented. That was my goal with Issue #26, in fact. I think that someone (maybe me, though you are welcome to take a crack at it) needs to take the time and figure out what date formats are currently supported and in what combinations, then write up that documentation.

From there, we can see which ones make sense to keep and how to re-write the parser to maintain the same functionality but be a bit easier to maintain and extent.

**Comment by pganssle** [comment]
Note: This bug was also reported on the launchpad as [issue #974463](https://bugs.launchpad.net/dateutil/+bug/974463).
