### ISSUE TITLE
Invalid date gets parsed successfully

### ISSUE THREAD

**Issue by mihaitodor** [dateutil/dateutil#290]
While cleaning up some poorly formatted dates, I noticed that `dateutil.parser.parse('22-23 February')` is not rejected with a ValueError and it produces `datetime.datetime(2022, 2, 23, 0, 0)`.

Is there any way to tell the parser to not accept two digit years?

**Comment by mihaitodor** [comment]
Potential workaround:

```Python
from dateutil.parser import parse, parserinfo

class NoTwoDigitYearParserInfo(parserinfo):
    def convertyear(self, year, century_specified=False):
        if year < 100 and not century_specified:
            raise ValueError('Two digit years are not supported.')
        return parserinfo.convertyear(self, year, century_specified)

parse('22-23 February', parserinfo = NoTwoDigitYearParserInfo())
```

**Comment by pganssle** [comment]
There is no built-in option to ignore 2-digit years built-in. Your solution seems perfectly adequate to me. The intention for a robust solution to this along with #214 and a string of other parser-related issues is that I'd like to move the parser over to something more extensible so that you can define whatever behavior you want on various aspects of the parser by subclassing `parserinfo`. Given that you can *already* extend `parserinfo` to address this particular issue, I think it's reasonable to close this issue.

**Comment by mihaitodor** [comment]
OK @pganssle, sounds good to me. Thanks for looking into it!
