### ISSUE TITLE
rrule is completely broken

### ISSUE THREAD

**Issue by kootenpv** [dateutil/dateutil#291]
```python
from datetime import datetime    
from dateutil.rrule import HOURLY
from dateutil.rrule import rrule
r = rrule(HOURLY, interval=1, byhour=(10))
r.between(datetime(2016, 9, 1, 1, 0), datetime(2016, 9, 6, 10, 0), inc=True, count=10)
# [datetime.datetime(2016, 9, 5, 10, 44, 34)]
```
What? 

I expect the output to be:

    # [datetime(2016, 9, 1, 10, 0), datetime(2016, 9, 2, 10, 0), ..., datetime(2016, 9, 6, 10, 0)]

**Comment by pganssle** [comment]
@kootenpv The implicit argument to `dtstart` is the current date, so your rule is implicitly starting *after* 9-1. This will work:

```python
from datetime import datetime    
from dateutil.rrule import HOURLY
from dateutil.rrule import rrule
r = rrule(HOURLY, interval=1, byhour=(10), dtstart=datetime(2016, 9, 1, 10))
r.between(datetime(2016, 9, 1, 1, 0), datetime(2016, 9, 6, 10, 0), inc=True, count=10)
```

However, I would also recommend on additional modification to the rule, which is to use a `DAILY` rule rather than an `HOURLY` rule. `HOURLY` will actually calculate all matching dates, but only yield those matching the `byhour` rule. If you actually want something with a daily interval, so it will probably be ~24x slower than the `DAILY` equivalent:

```python
from dateutil.rrule import DAILY
r = rrule(DAILY, interval=1, byhour=(10), dtstart=datetime(2016, 9, 1, 10))
```

**Comment by kootenpv** [comment]
@pganssle I understand now. Even though I was vaguely aware of the `dtstart`, I assumed that "between" will overwrite this. Somehow it seems like `dtstart` should not be part of the rule, but I guess that's a personal preference. Thanks for the elaborate answer!

**Comment by pganssle** [comment]
@kootenpv `dtstart` is a fundamental part of the rule, because it serves as the basis for the recurrences. I don't recall precisely, but I wouldn't be surprised if the RFC doesn't specify a way for rules to propagate "backwards" starting at the start date. `between` returns dates matching the rule between two dates, which doesn't apply to dates before `dtstart`.
