### ISSUE TITLE
upgrading to timezone database 2016g

### ISSUE THREAD

**Issue by toppare** [dateutil/dateutil#298]
https://www.iana.org/time-zones

**Comment by pganssle** [comment]
@toppare Generally the time zone database gets updated when a new release is pushed. I'm working towards a way to more easily update the timezone database out-of-band so that dateutil releases are not tied to timezone database releases, but that's not totally done yet.

You can find the latest version of the tz-database in a dateutil-consumable way here:

https://dateutil.github.io/tzdata/

Easiest way to do it would be to clone the github repository, check out the latest release, download https://dateutil.github.io/tzdata/zonefile_metadata/zonefile_metadata.json to the dateutil directory, type `python updatezinfo.py`, then type `python setup.py install`.
