### ISSUE TITLE
RFC822 timestamp using GMT is parsed into BST if local time is UK time

### ISSUE THREAD

**Issue by JordonPhillips** [dateutil/dateutil#318]
The following code snipped prints `True` unless the machine is using UK time.

```python
from datetime import datetime
from dateutil.parser import parse
from dateutil.tz import tzutc


d1 = datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())
d2 = parse('Wed, 02 Oct 2002 13:00:00 GMT')
print(d1 == d2)
```

It appears that at [this point](https://github.com/dateutil/dateutil/blob/master/dateutil/parser.py#L605) in the parse function, the parser sees that local time is one of `('GMT', 'BST')` because in the Summer the UK uses BST (GMT+1).

Source issue: boto/botocore#1070

**Comment by pganssle** [comment]
This is a tricky situation, because the API is pretty clear about the fact that it's going to check your local time zones for valid zone names to parse. The real issue is that this is really fuzzy and context-dependent behavior. I'd love to deprecate it at some point in the future and make it a default-off option.

That said, I don't think this should be removed as is, because it would actually remove existing functionality with no way to replicate the old behavior, whereas currently you can get your desired behavior this way:

```python
from datetime import datetime
from dateutil.parser import parse
from dateutil.tz import tzutc


d1 = datetime(2002, 10, 2, 13, 0, tzinfo=tzutc())
d2 = parse('Wed, 02 Oct 2002 13:00:00 GMT', tzinfos={'GMT': tzutc()})
print(d1 == d2)
```

This is generally advisable, because if you notice, RFC822 also specifies 'EST', 'EDT', and a number of other zones, none of which can be parsed _at all_ by `dateutil.parser` unless they are the local zone, (and never will be) for ambiguity reasons. The real lesson is that you need to provide the context yourself if you know it.

That said, there is _one_ possible tweak that I think I would be comfortable with, which is that we can improve the time zone parser logic such that when it decides to assign `tzlocal()` it will check if the time zone that actually gets assigned is the time zone we were expecting, e.g.: `dt.replace(tzinfo=res.tzname).tzname() == res.tzname`, and if not, see if there's another way to parse it that _does_ create a time that exists. This same logic should also be used to assign whether or not the parsed date has the `fold` attribute, but I will make a separate issue for that.
