### ISSUE TITLE
Rename package name on PyPI

### ISSUE THREAD

**Issue by mindojo-victor** [dateutil/dateutil#327]
It's strange that the package name on PyPI is `python-dateutil`. It's implied that PyPI hosts only python packages, why prefixing the name with `python-`?

`dateutil` is available: https://pypi.python.org/pypi?%3Aaction=search&term=dateutil&submit=search

You could upload the newest version with the new name, so that when people will upgrade it, they will change package name. Or support two identical packages for several years -- one with the current `python-dateutil` name and a new one `dateutil`.

I think the current package name is causing this in PyCharm:
![image](https://cloud.githubusercontent.com/assets/17159503/20646495/67e4c9f2-b482-11e6-90ce-9fbfc0ea7787.png)
Though I have this in my `requirements.txt`:
```
python-dateutil==2.6.0
```

**Comment by pganssle** [comment]
@mindojo-victor I don't know anything about pycharm, but that seems like a bug in pycharm more than in dateutil. I really, really don't think we should try and rename the package, it would be a ton of pointless work for all downstream users.

I'm somewhat sympathetic to the idea of squatting on the `dateutil` package and just posting a package there that fails with an error saying, "Hey, the package is called python-dateutil!"

Theoretically, we could host a mirror at `dateutil`, but that would needlessly complicate the package management, and then it could be a mess if we forget to update one or the other package and a quarter of people are using `dateutil` instead of `python-dateutil` you'll get weird and inconsistent behaviors.

**Comment by mindojo-victor** [comment]
Ok, thanks for the feedback.

**Comment by mindojo-victor** [comment]
I just caught myself several times, that I forgot that the package in PyPI is called `python-dateutil`, not `dateutil`.

**Comment by pganssle** [comment]
@mindojo-victor Yes, if it were up to me I would have called the package `dateutil` in the repository. I assume that it was originally called `python-dateutil` to distinguish it from other languages' datetime utility libraries.

**Comment by oroulet** [comment]
fyi it is easy to upload an empty package called python-datetutil to pip after renaming to dateutil so things do not break for anybody. just did it for freeopcua -> opcua

**Comment by jbrockmendel** [comment]
I'm -1 on outright renaming, but would be OK with grabbing the alias, in part to prevent bad actors from spoofing.

**Comment by pganssle** [comment]
Renaming is not happening for the reasons detailed above, plus the fact that the `dateutil` package is already owned by someone else who presumably grabbed it to prevent namespace confusion, and I have no access to it. The situation is what it is and unless in the future PyPI adds a way to define packages as simple aliases, it's pointless to make any fuss about it.

**Comment by oroulet** [comment]
For some reasons this bug is one of the first page returned by Google for pypi rename. At least i have documented a solution now.

**Comment by Kenny2github** [comment]
@oroulet yes, thank you ;)
