### ISSUE TITLE
Infinite loop in rrule.rrule if count is set to 0

### ISSUE THREAD

**Issue by vaultah** [dateutil/dateutil#329]
`rrule.rrule` yields values indefinitely if the `count` argument is set to 0. Example:

```
In [2]: for x in rrule.rrule(freq=rrule.DAILY, count=1): print(x)
2016-12-01 17:53:11

In [3]: for x in rrule.rrule(freq=rrule.DAILY, count=0): print(x)
2016-12-01 17:53:15
2016-12-02 17:53:15
2016-12-03 17:53:15
...
```

Even if 0 is not an acceptable value for that parameter, this looks like a bug.

**Comment by pganssle** [comment]
@vaultah Yes, this is definitely a problem. It's not so much an infinite loop, though, since `rrule` is by defauly an infinite generator anyway.

I haven't looked at where it's happening in the code, but I suspect that there's a check like `if count` somewhere in there, expecting that `count` will either be a positive integer or `None` (unspecified). I think maybe we can do something like:

```python
if count is not None and count < 1:
    raise ValueError('count parameter must be positive')
```

Then we just need to add tests for `count=0` and `count=1`.

Feel free to make a PR, otherwise I'll try and handle this before the next release.
