### ISSUE TITLE
Non Local timezones not supported by parse() with ignoretz=False

### ISSUE THREAD

**Issue by twildeboer** [dateutil/dateutil#345]
Note in the examples below that only the PST date gets a tzinfo when ignoretz=False is used. And it is tzlocal(). (I am in the PST timezone). For CST and EST, ignoretz=False still produces a naive datetime.
```
>>> parse("1996.07.10 AD at 15:08:56 PST", ignoretz=True)
datetime.datetime(1996, 7, 10, 15, 8, 56)
>>> 
>>> parse("1996.07.10 AD at 15:08:56 PST", ignoretz=False)
datetime.datetime(1996, 7, 10, 15, 8, 56, tzinfo=tzlocal())
>>> 
>>> parse("1996.07.10 AD at 15:08:56 CST", ignoretz=False)
datetime.datetime(1996, 7, 10, 15, 8, 56)
>>> 
>>> parse("1996.07.10 AD at 15:08:56 EST", ignoretz=False)
datetime.datetime(1996, 7, 10, 15, 8, 56)
```

**Comment by pganssle** [comment]
@twildeboer Yes, this is the standard, deliberate behavior. In my opinion, even `PST` should not be processed to `tzlocal()`, but there are several places where `parse` makes the assumption that the dates you are parsing were, unless otherwise specified, generated in the locale of the program parsing them.

The reason why the other zones are not parsed is that three-letter zone names do not uniquely identify their respective zones - consider that `CST` could be China Standard Time, Cuba Standard Time or Central Standard Time, so additional context is required. For PST, the implicit context is "this probably refers to the PST that I know about" - which may or may not be valid.

The right thing to do when processing zones of this sort is to give them *explicit* context by passing a dictionary or function to the [`tzinfos`](https://dateutil.readthedocs.io/en/latest/parser.html#dateutil.parser.parse) argument mapping the 3-letter abbreviations to the appropriate `tzinfo` objects (e.g. `tzinfos={'PST': gettz('US/Pacific'), 'PDT': gettz('US/Pacific')}`).

**Comment by twildeboer** [comment]
Got it. Thanks for the quick response. 
For anyone else, this link is useful if you're willing to tolerate possible misinterpretations: http://stackoverflow.com/a/11145008/4560473
