### ISSUE TITLE
tzical is not thread-safe

### ISSUE THREAD

**Issue by Unrud** [dateutil/dateutil#428]
```
Traceback (most recent call last):
...
  File "dateutil/tz/tz.py", line 1109, in utcoffset
    return self._find_comp(dt).tzoffsetto
  File "dateutil/tz/tz.py", line 1062, in _find_comp
    return self._cachecomp[self._cachedate.index((dt, self._fold(dt)))]
IndexError: list index out of range
```

``_cachedate`` and ``_cachecomp`` are not protected by a lock.

**Comment by pganssle** [comment]
I am planning some improvements to `tzical` so that it is able to more seamlessly reuse the `rrulebase` subclasses (which have thread-safe caches). I'm also planning on reworking time zone caches (see #342), so I think this will go away when that is done.

@Unrud Are you able to reproduce this issue at will? Do you have code that does so?

I think one of the bigger issues here is how to test for whether or not this is fixed rather than just being logically satisfied that it is.

**Comment by Unrud** [comment]
> Are you able to reproduce this issue at will? Do you have code that does so?

I don't have an isolated test case. The exception happened while parsing and serializing iCalendar with VObject in parallel.

> I think one of the bigger issues here is how to test for whether or not this is fixed rather than just being logically satisfied that it is.

Especially if it doesn't throw an exception and instead silently uses a wrong entry from the cache.

**Comment by pganssle** [comment]
> Especially if it doesn't throw an exception and instead silently uses a wrong entry from the cache.

This wouldn't be an issue in a unit test, since the output is known.
