### ISSUE TITLE
lt gt does not work after +,- operates

### ISSUE THREAD

**Issue by crackevil** [dateutil/dateutil#467]
see case with python 2.7:

a=relativedelta(minutes=10)+relativedelta(minutes=5)
b=relativedelta(minutes=15)
c=relativedelta(minutes=50)
print b<c

comment "a" out, can get a different result

**Comment by jbrockmendel** [comment]
It looks like `relativedelta` doesn't define `__le__` at all, so this comparison is not well-defined.  It may be that it should raise (well, maybe not in this case since they are comparable, but in the more general case).

**Comment by pganssle** [comment]
@crackevil See #350

**Comment by pganssle** [comment]
By the way, since `relativedelta` does not implement `__lt__` or any other comparator, the default behavior is that `a < b` if `id(a) < id(b)`, so those comparison operators are arbitrary. Those objects are ordered by their location in memory, not their values.

**Comment by crackevil** [comment]
That's fine. I think it's why timedelta of datetime package limit its parameters. But relativedelta has normalize function if I did not get wrong. Can it be the same logic to deal with month and year by means under lt & gt?

**Comment by pganssle** [comment]
@crackevil `normalized` just converts *fractional* well-defined quantities into the equivalent combination of integer sub-units, e.g. 0.5 days -> 12 hours, etc. There isn't a well-defined conversion from months->days, since "month" generally means something like "until the same day in the next calendar month", which depends on the left-hand-side of the equation, so `relativedelta(months=1)` and `relativedelta(days=30)` don't have a fixed ordering, since `(datetime(2017, 1, 15) + relativedelta(months=1)) > (datetime(2017, 1, 5) + relativedelta(days=30))`, but `(datetime(2017, 2, 15) + relativedelta(months=1)) < (datetime(2017, 2, 15) + relativedelta(days=30)`.

You are free to subclass `relativedelta` and implement `__lt__` and `__gt`__ as desired on the subclass if you want a specific ordering. Alternatively, if you don't care about the details and don't want to subclass, you could just add both relativedeltas to an arbitrary date (maybe the unix epoch `datetime(1970, 1, 1)`) and compare the results, like I did above. So long as the date is consistent, it should have more-or-less consistent results.

**Comment by crackevil** [comment]
@pganssle thanks, your approach is smart and helpful
