### ISSUE TITLE
How to handle 00 values in month and day

### ISSUE THREAD

**Issue by supritashankar** [dateutil/dateutil#473]
I have this as my date - `+1960-00-00T00:00:00Z` and I am not able to parse it.

This is what I have tried so far
```
import dateutil.parser
dateutil.parser.parse("+1960-00-00T00:00:00Z")
```
I get the error `Unknown string format`
Cannot find any docs around this. Any help would be appreciated!

**Comment by pganssle** [comment]
What do you expect the output of that to be? 0 is not a valid value for either month or day.

**Comment by supritashankar** [comment]
@pganssle I just want to get the year value.

**Comment by pganssle** [comment]
@supritashankar Hm.. I am not sure there will be a satisfactory resolution to this, since in a lot of cases it's not clear exactly how to handle a given string if some of the values are just straight up invalid. I was going to suggestin `fuzzy=True` here, since I figured the parser would find the `00` and assume they are non-date components, but what actually happens is that it raises `ValueError: month must be in 1..12`.

It's possible that this problem is fixable, in which case it *might* be fixed at some point.

For now, if you just care about the year and it's all in the same format, just do this: `int(dtstr[1:5])`

**Comment by supritashankar** [comment]
Yes there seems to be no other way :/ I didn't want to do. Closing this on the same note.
