### ISSUE TITLE
parse time string with timezone failed on django shell or ipython shell

### ISSUE THREAD

**Issue by littleday** [dateutil/dateutil#508]
Hi,

I am trying to parse a time string to datetime.
Here is a code I used for testing:
parser.parse("2017/10/03 09:59:52 PDT")

It worked in python shell, the return value has the correct timezone info. But it didn't work with iPython or Django shell. The return value has no timezone info.

Thanks

**Comment by pganssle** [comment]
@littleday I'm not entirely sure why this would be different between the python shell and IPython or Django, but I'm guessing those other shells are on different machines, and that the first machine is set to Pacific time.

The reason for this is because "PDT" and other 3-letter acronyms are not sufficient to uniquely specify a time zone, as many or most of them are not unique (and we don't have a great way of maintaining a mapping, anyway). These are really only useful *in context*, and so you have to supply the context for the parser. One of the places the parser looks for context is in the time zone abbreviations your machine exposes through `time.tzname`, and if it finds the abbreviation there, it says, "Oh, this must be in your local time" and attaches `tzlocal`. Otherwise if it *looks* like a time zone abbreviation and doesn't find it anywhere, it just skips over it.

To make it work consistently on any machine, do this:

```python
from dateutil import tz
from dateutil.parser import parse
PT = tz.gettz('US/Pacific')
tzinfos = {'PST': PT, 'PDT': PT}
dt = parse("2017/10/03 09:59:52 PDT", tzinfos=tzinfos)
```

Similarly if you want to add other abbrebiations, add them in the `tzinfos` dictionary. Alternatively, you can write a function that takes `tzname` abbreviations and returns tzinfo objects.

Hope this is helpful!

**Comment by pganssle** [comment]
Closing this because I've answered the question and it's not an ongoing issue, but feel free to continue responding here.
