### ISSUE TITLE
Implement __format__ for relativedelta

### ISSUE THREAD

**Issue by lynncyrin** [dateutil/dateutil#535]
It'd be rad to have a `relativedelta.shortened()` function that turns output like

```
relativedelta(days=-26, hours=-4, minutes=-18, seconds=-4, microseconds=+474948)"
```

into

```
relativedelta(days=-26, hours=-4)"
```

via clipping all the attributes beyond the 2nd

EDIT:

actually, even better would be more focused human readable output, like

```
26 days, 4 hours
```

---

100% willing to add this myself, if the maintainers would be interested in adding it

**Comment by pganssle** [comment]
@lynncyrin I've renamed the issue here because I *think* that your use case is mostly about a truncated *string* representation, is that right?

I don't think it would be a good idea to just have `relativedelta.shortened()` because the semantics of that are somewhat unclear. `relativedelta`, unfortunately, is a chimera class that is a mixture of "partial dates" and "calendar deltas", see #449 (refactoring out `partialdatetime`) and #524 (refactoring out `calendardelta`), and so there's no clear hierarchical ordering that can be foreshortened in an obvious way.

For the string-representation question, I think the way forward is to implement `__format__` on `relativedelta`, and come up with a format-specification mini-DSL to specify components (I guess [PEP 3101](https://www.python.org/dev/peps/pep-3101/) is the best documentation I can find for this). This has some of the problems inherent in issue #444 (no existing standard), and we'll probably want to get those two formatting mini-specs to at least *partially* agree.

We may want to see what [pandas' offsets](https://pandas.pydata.org/pandas-docs/stable/timeseries.html#dateoffset-objects) are doing and if they have any formatting tips. That said when making trade-offs between being useful and being correct, `pandas` tends to choose useful and `dateutil` tends to choose "correct" (in the abstract), so it may be that the philosophies don't mesh. @jbrockmendel  Any thoughts?

@lynncyrin I'd totally welcome a contribution, but I will warn you that unfortunately I've been at least partially paralyzed with indecision about formatting specs lately (see #444 and #454), so it might not be an amazingly fun contribution to make (since it is mostly about digging up standards and making the case for them, and trying to harmonize various representations - and likely it will be a while before anything gets merged).

**Comment by pganssle** [comment]
@lynncyrin One other thing, the other possibility here is to implement the bit masking operators like `&` and `|` so that you can easily do something like `relativedelta(hours=4, minutes=9) | rdmask(hours=True) == relativedelta(hours=4)`. Either you or I can make a separate issue for discussion of this possibility. I am not opposed to it, but that's another one where it has serious API implications, so it will need to be thought about carefully.

**Comment by lynncyrin** [comment]
I'm closing a bunch of my older github issues ♻️  feel free to open a new issue describing this same change! Or re-open this one, if someone is still interested in working on it 📝
