### ISSUE TITLE
Prepocessing results of timelex.split

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#541]
Looking at the test case `timestr = '5:50 A.M. on June 13, 1990'` which incorrect identifies the 'M' in 'A.M.' as a tzname, I'm thinking it might make sense to avoid this particular problem within timelex.split so that "A.M." is identified as a single token.  A few similar cases come to mind: "P.M.", "A.D.", "B.C.".  Thoughts?

**Comment by jbrockmendel** [comment]
@pganssle I'm thinking about implementing something for this, want to run it by you first since it may run up against your aversion to hard-coding strings.  There are two cases I'd like to catch at tokenization time:

1) [AP].M.
2) "[A-Za-z]/[A-Za-z]" --> retain "US/Eastern" instead of ["US", "/", "Eastern"].

Thoughts?

**Comment by pganssle** [comment]
@jbrockmendel The problem with this and many of your other attempts at structural changes to the parser is that they are piecemeal and tweak around the edges, which is exactly what I *do not want*. I will need some time to learn more about the general theory of parsing before I'm ready to make any decisions about how the parser will change, unfortunately.

Unless you want to present a fully-featured parser as a *fait accompli* with an interface I would be happy with, I imagine most of these suggestions and PRs will languish for a while. I would probably not recommend this (unless you prefer to just write a separate parser for reasons other than getting it merged into `dateutil`), as we seem to have markedly different sensibilities about what makes for a good API.

I am, generally speaking, wary of doing parsing in the lexer. I think part of the problem is that `timelex` seems to actually just be a tokenizer, not a proper lexer (e.g. a tokenizer that attaches some additional context to the tokens). I don't understand the various techniques of lexing and parsing and when to apply them well enough to know what the right solution is here.

Also, what exactly is the point of pre-processing these like this? Both the tokens and the separators are available to the parser, and it frequently re-combines them as necessary. Why is this case special such that we should violate this separation of concerns?

**Comment by pganssle** [comment]
>I think part of the problem is that timelex seems to actually just be a tokenizer, not a proper lexer (e.g. a tokenizer that attaches some additional context to the tokens). 

Sorry, looking at `timelex` again, I'm wrong, it does in fact maintain some additional state / context about the tokens. As I mentioned earlier, I'm not familiar enough with the theory of parsing to know if this is the right level of abstraction, but I suspect that it *may* be close to it - most of what we care about, context-wise, is in the semantic meaning of the tokens, which I think would normally done as part of the construction of an abstract syntax tree (though we're not parsing a compiler with a well-defined grammar, so I'm not sure how well the analogy to that sort of parser holds).

**Comment by jbrockmendel** [comment]
> Also, what exactly is the point of pre-processing these like this? Both the tokens and the separators are available to the parser, and it frequently re-combines them as necessary. Why is this case special such that we should violate this separation of concerns?

After `timelex.split` the parser _doesn't_ recombine tokens.  It occasionally examines neighboring tokens for contextual inference, but assumes that each individual token is "right".  e.g. all of the "is this a valid XYZ?" checking is based on "is this token included in the dictionary for XYZ?"  Which is why in the status quo "US/Eastern" and "A.M." can never be correctly identified by the parser.  We _could_ try to re-combine these within `parse`, but after looking at it I determined it's much simpler to avoid splitting them in the first place.

> I am, generally speaking, wary of doing parsing in the lexer. 

At least in the short term I agree.  We have zero tests in test_internals for the tokenization.  If at any point we _do_ agree to change anything there, we should have a test suite for it to avoid regressions.

That said, the tokenization is likely the part of the process that is the most amenable to being formally specified.  This might also be a good candidate for behavioral-style testing+fuzzing.

> I will need some time to learn more about the general theory of parsing before I'm ready to make any decisions about how the parser will change, unfortunately.

Since this has come up in a couple of threads, can you start an issue or project or something so we can discuss it in one place?  If a formal approach like this is feasible it'd be awesome and I'd like to help (though I'm not all that confident).  

Short-medium term, I'm not sure how to do bug-fixes that _aren't_ "tweaks around the edges".  (I am very much counting 

```
>>> parser()._parse('5:50 A.M. on June 13, 1990')[0]
_result(year=1990, month=6, day=13, hour=5, minute=50, tzname=u'M', ampm=0)
```

as a bug)

> as we seem to have markedly different sensibilities about what makes for a good API.

I'm chalking this up to a learning experience, being the junior team-member and figuring out how to work around a sometimes-frustrating situation.  I appreciate you bearing with me as I get up the learning curve.

**Comment by pganssle** [comment]
> After timelex.split the parser doesn't recombine tokens. It occasionally examines neighboring tokens for contextual inference, but assumes that each individual token is "right". e.g. all of the "is this a valid XYZ?" checking is based on "is this token included in the dictionary for XYZ?"

Hmm, I guess I assumed that the `0.5` stuff was being tokenized, but I can see now that it's explicitly allowed for. In fact, some of the tokenization stuff is already happening in the parser.

I suppose I can't think of any reason why it matters if `A/B/C` is considered a single token, though if you look at [this approach](https://github.com/dateutil/dateutil/pull/227/files#diff-ed798069162e7ab7db9a45da6c4a076fR996), it seems a little better to me because they're building the string up dynamically based on whether it matches prefixes in the time zone list.

I think the only reason I didn't merge that one was because I wanted to convert the lookup table into a radix tree instead of whatever it is now.

> Short-medium term, I'm not sure how to do bug-fixes that aren't "tweaks around the edges".

Yes. I think there have been a few, like the `%b` one and such, but my point is that the biggest "bug" that people care about it #402, which was actually caused by some naive changes to an untested and undocumented feature of the weird interface. Probably the second most important bug is #214. Probably the third biggest problem with the parser is that it is *slow*. The first two are interface decisions, and I think all three of them require that we have a good understanding of the fundamental mode of operation of the parser. Not that it's not valuable to fix these bugs, but I'm hesitant to make any *significant* changes to the mode of operation  and, more importantly, to the public interface and public behavior, because I don't want to constrain our future decisions about interface design.

> > as we seem to have markedly different sensibilities about what makes for a good API.
>
> I'm chalking this up to a learning experience, being the junior team-member and figuring out how to work around a sometimes-frustrating situation. I appreciate you bearing with me as I get up the learning curve.

To be honest, I suspect it's that you seem to do a lot of work with `pandas`, which has an "easy" API that works well for interactive programming, but in the end it's quite unwieldy and adds a lot of complexity and overhead - both from a maintenance perspective and at runtime. In general, I prefer `dateutil` to be closer to the standard library, and to have, as much as possible, a clean API with separation of concerns, etc. `pandas` also has a sort of "advantage" in that they make no real claims about their stability. They've been on `0.x` for *years* (and in semver `0.x` has the special meaning of being alpha - so even minor releases can break backwards compatibility).

Either way, it's a totally different API design philosophy.

**Comment by jbrockmendel** [comment]
> To be honest, I suspect it's that you seem to do a lot of work with pandas, which has an "easy" API that works well for interactive programming

Well let's not forget about `statsmodels`, which is an entirely different flavor of chaos.

> Hmm, I guess I assumed that the `0.5` stuff was being tokenized

I'm missing something.  What is "the `0.5` stuff"?

> though if you look at this approach, it seems a little better to me because they're building the string up dynamically based on whether it matches prefixes in the time zone list.

I'm not entirely opposed to that approach, but splitting the string and then re-combining it and checking and... seems a lot more complicated than just avoiding "incorrectly" splitting in the first place and checking dict-inclusion like we do now (or will/should pending #554).  Let's avoid getting side-tracked on this.

> which was actually caused by some naive changes to an untested [...] Probably the third biggest problem with the parser is that it is slow

With few exceptions (namely #540 which I think is an important bug) I am 100% on board with the idea of prioritizing better testing and profiling before embarking on any other changes.

In that vein, I propose we re-purpose this Issue towards formalizing the spec for _timelex and implementing tests for it in test_internals.

**Comment by pganssle** [comment]
> I'm missing something. What is "the 0.5 stuff"?

I meant like `0.5s` or something - I thought it was getting tokenized to `[0, '.', 5, 's']`, and then re-combined, but the lexer is actually actively keeping those together. The analogy to keeping `char-'/'-char` tokens together in the same way we do with digit-dot-digit, and failing to come up with any examples, so that's something in favor of your idea. Possibly `char-dot-char` can also be kept together? I'll have to look more closely.

> With few exceptions (namely #540 which I think is an important bug) I am 100% on board with the idea of prioritizing better testing and profiling before embarking on any other changes.

Well, the issue in that case was that actually I didn't realize how people were using the library, and I now suspect that the way `yearfirst` and `dayfirst` worked was a deliberate feature. Assuming it was an accidental feature, I'm not sure there's any way to discover those other than to be told by downstream users.

One possibly interesting thing to do would be to try and find some of the biggest users of `dateutil` and make PRs against their repos adding a version of the tests that runs against master. That way, they'll start seeing broken builds before we cut any releases.

**Comment by jbrockmendel** [comment]
> Well, the issue in that case was that actually I didn't realize how people were using the library [...]

The issue I was referring to #540 is unrecognized timezones being silently ignored.  Are we talking about the same thing?  If so, I do not understand how the dayfirst/yearfirst kwargs come into it.

Based on #581 I think we should prioritize making the spec explicit and testing the internals.  That and (somehow) profiling `_timelex` should come before _changing_ `_timelex`.

**Comment by pganssle** [comment]
> The issue I was referring to #540 is unrecognized timezones being silently ignored. Are we talking about the same thing? If so, I do not understand how the dayfirst/yearfirst kwargs come into it.

Just that it's an analogous situation - it's quite possible that some people *like* this behavior and are in fact counting on it. Considering that that's the behavior of `strptime`'s `%Z` right now, I want to tread cautiously.

Here's a compromise: Let's raise a warning. If no one comes and says, "Hey, we're really counting on this feature!" in 6 months, we'll switch it over to an error.

**Comment by jbrockmendel** [comment]
Pivoting back to the `_timelex` discussion: are you on board with the idea of specifying a formal spec for _timelex so we can test (hypothesis might be especially useful here) the tar out of it before making any potential changes.

Especially in light of #581 showing that in some cases regexp can significantly improve performance, there might be several types of upside here.

**Comment by pganssle** [comment]
> Pivoting back to the _timelex discussion: are you on board with the idea of specifying a formal spec for _timelex so we can test (hypothesis might be especially useful here) the tar out of it before making any potential changes.

That would have been fine when `_timelex` was written (before anyone was using it), but we're victims of Hyrum's law at this point. To a large extent we need to be descriptive about what `_timelex` does, not prescriptive, so any spec other than an exact description of what the current implementation does would just be guesswork, and if it breaks something in the wild then it's the spec that has to change not the implementation.

I'm also not entirely convinced that `_timelex` will survive my "read more about parsing" research phase. It seems like a somewhat naive way to do things.

**Comment by jbrockmendel** [comment]
>  To a large extent we need to be descriptive about what _timelex does

Yep, that's the idea.  I'm thinking timelex.split is simple enough that we can write hypothesis/fuzzing tests that will uniquely describe the function.  Assuming this is possible, then in the future if/when we _do_ change timelex.split, we can be confident the we haven't introduced accidental changes along with the intentional ones.

> I'm also not entirely convinced that _timelex will survive my "read more about parsing" research phase. It seems like it might be a somewhat naive way to do things.

I'm entirely supportive of this goal, but have a heavy-tailed prior as to how long it will take, so would like to keep forward momentum on bugfixes in the shorter-run.  Thorough testing for timelex.split's existing behavior should come before any attempts to change/"fix" it.

Seems like it'll be easier to implement this on my own and show a ~finished product that keep trying to describe it.  Closing.
