### ISSUE TITLE
Sensible defaults for tzinfos

### ISSUE THREAD

**Issue by jbrockmendel** [dateutil/dateutil#575]
So we don't want to hard-code tzinfos, but I claim that the following or something like it would be a Sensible Default for tzinfos (at least for US users)

```
tzinfos_us = {
    'PST': dateutil.tz.gettz('US/Pacific'),
    'PDT': dateutil.tz.gettz('US/Pacific'),
    'PT': dateutil.tz.gettz('US/Pacific'),
    'MST': dateutil.tz.gettz('US/Mountain'),
    'MDT': dateutil.tz.gettz('US/Mountain'),
    'MT': dateutil.tz.gettz('US/Mountain'),
    'CST': dateutil.tz.gettz('US/Central'),
    'CDT': dateutil.tz.gettz('US/Central'),
    'CT': dateutil.tz.gettz('US/Central'),
    'EST': dateutil.tz.gettz('US/Eastern'),
    'EDT': dateutil.tz.gettz('US/Eastern'),
    'ET': dateutil.tz.gettz('US/Eastern')}
```

There are others that are pretty close to unambiguous: BRST, CEST, ...  If this would make it easier for a large fraction of users to Do It Right, then we should consider providing a shortcut to something like this.

**Comment by pganssle** [comment]
Not really interested in this, because it makes things harder to debug. If anything,  I want to go the other direction and make it so that it doesn't check your local time zone abbreviations when parsing.

This leads to a big report / SO question about every month or so like, "Why does EST work but PST doesn't?!?!"

This will exacerbate that problem.

**Comment by jbrockmendel** [comment]
> make it so that it doesn't check your local time zone abbreviations when parsing

This part I see the appeal of; the fact that you and I get different parse results based on our local timezones definitely makes debugging harder.

But I don't see why this would exacerbate the problem.  For one thing, I'm suggesting an opt-in, maybe something like passing `tzinfos="US"`.  For another, it specifically means that EST, PST,... will be parsed without depending on what timezone the user is in.

Also keep in mind that if/when #540 goes in, a lot of previously-silent bugs will start raising.  I _strongly_ suspect that `parse("2017-12-08 12:05 EST")` is a common case on which we currently incorrectly+silently return a naive datetime for non-EST users.

While I think the `"Why does EST work but PST doesn't?!?!"` concern is misplaced, I can imagine a variant `"Why does CEDT work but Transylvanian Obscure Time doesn't!?!"`.  That's a shortcoming that I'd be OK with, but can understand the reasoning against.

**Comment by pganssle** [comment]
Ah, sorry, I'll review more formally when I get back. I'm much less opposed to shipping tzinfos localized packs than to having "sensible defaults".

**Comment by pganssle** [comment]
I'd call this a *maybe*. I'm already considering making `zoneinfo` an optional add-on maintained in a separate package. I wouldn't be a opposed to a separate package that provides some sensible groupings (like "US", "European", "Asian").

The idea of `tzinfos='US'` is, of course, horrifying, because there's zero reason for that to be a hard coded string when we could simply provide a dictionary or `tzinfopack` object or something, so it would look like `tzinfos=tzpacks.US`. (Don't care for the name I just chose there, but you get the point).

**Comment by jbrockmendel** [comment]
>  The idea of tzinfos='US' is, of course, horrifying, because there's zero reason for that to be a hard coded string when we could simply provide a dictionary or tzinfopack

The benefit of `tzinfos='US'` is that when users start complaining that they are getting errors from EST/PDT/... where "it used to Just Work", the solution can be "just add `tzinfos='US'` without any additional "simply import this other thing and then..."

But my preference for the easy API is almost certainly weaker than your preference against hard-coding strings.  I'll be pretty happy with any reasonable implementation.

**Comment by pganssle** [comment]
That is not a benefit over just having a separate dictionary, and all the downsides are there. There's no *real* advantage. There's maybe a mild convenience advantage to putting a bunch of time zone pack constants in the `tz` module itself, but I'd put the most minor possible weight on that.

**Comment by jbrockmendel** [comment]
Let's revisit this after #540.  Closing.

**Comment by pganssle** [comment]
@Harmon758 The parser needs an overhaul in a way that is totally blocked on me learning more about the theory of parsing, unfortunately, so it's not entirely clear the right way to proceed with this.

That said, I don't think it will ever go in the main `dateutil` package. Instead, I'd like to start a new project, something like `dateutil.zonepacks`, which is importable separately from `dateutil` and provides mappings and/or functions for common locales.

**Comment by jbrockmendel** [comment]
> The parser needs an overhaul in a way that is totally blocked on me learning more about the theory of parsing

@pganssle is there an Issue to discuss this (dont want to derail this thread)?  I'm curious if there's progress or an ETA, have been holding off on parsing PRs in part because of this blocking.

w/r/t @Harmon758's question, is this a matter on which sufficient community consensus could sway your thought process?

**Comment by pganssle** [comment]
@jbrockmendel Like, to include it by default? I'm more or less convinced to create a new package that does just this, I just don't want to jump the gun because the time zone parsing stuff is pretty annoyingly limited right now.

**Comment by jbrockmendel** [comment]
> Like, to include it by default?

Yes.  It isn't clear to me that default tzinfos are "big" enough to merit a new package (nor that they would be really useful independent of dateutil).  Do you envision this as being something more than a handful of {str: tzinfo} dictionaries?

**Comment by pganssle** [comment]
It's a matter of scope. I want to move all "data" out of the main `dateutil` package, including the `zoneinfo` package, so that those can be updated without a change to the underlying "code" packages.

Also, this is of course very US-centric, and might be trickier than you'd think.

Consider:

```python
>>> from dateutil import tz
>>> from datetime import datetime
>>> PHO = tz.gettz('America/Phoenix')
>>> datetime(2018, 1, 1, tzinfo=PHO).tzname()
'MST'

>>> datetime(2018, 7, 1, tzinfo=PHO).tzname()
'MST'

>>> DEN = tz.gettz('America/Denver')
>>> datetime(2018, 1, 1, tzinfo=DEN).tzname()
'MST'

>>> datetime(2018, 7, 1, tzinfo=DEN).tzname()
'MDT'
```

Under certain assumptions, you can more or less map `MST` to `'America/Denver'`, but if it's in the summer and you found `'MST'`, the "sensible default" is `America/Phoenix`, I suppose (either that or you assume that it's a malformed time zone).

This sort of thing is not as clean as you might suspect.

**Comment by jbrockmendel** [comment]
Separating the "data" from the code for versioning purposes makes sense.  The end result should still have a single "pip install X" that Just Works; that may mean separting both dateutil[data] and dateutil[code] and having the python-dateutil "namespace" superset both.

> This sort of thing is not as clean as you might suspect.

Sounds like we should start putting this together and iterate towards the desired implementation.  We could get the implementation nailed down first in a non-master shared-branch and worry about the namespace later on.
