### ISSUE TITLE
Parsing with too big year

### ISSUE THREAD

**Issue by cedk** [dateutil/dateutil#58]
When parsing a string for which the year part will be a too much big integer, an OverFlowError is raised:
```
Traceback (most recent call last):
  File "tryton/common/datetime_.py", line 151, in focus_out
    self.parse()
  File "tryton/common/datetime_.py", line 87, in parse
    date = date_parse(text, self.__format).date()
  File "tryton/common/datetime_.py", line 26, in date_parse
    return parse(text, dayfirst=dayfirst, yearfirst=yearfirst, ignoretz=True)
  File "/home/ced/.local/lib/python2.7/site-packages/dateutil/parser.py", line 697, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/ced/.local/lib/python2.7/site-packages/dateutil/parser.py", line 310, in parse
    ret = default.replace(**repl)
OverflowError: Python int too large to convert to C long
```
I think the error should be catch and raised as a ValueError.

**Comment by pganssle** [comment]
Why does it make more sense as a ValueError? The real problem is that it's being passed to a function as a 32 but integer, which is an overflow error. The value isn't conceptually incorrect, it's just an issue with the implementation.

**Comment by cedk** [comment]
It doesn't but as user of the library, it is difficult to know what are the possible exceptions.
At first sight, we can assume it will only raise ValueError but there is this case. So I don't know if in my code I must catch ValueError and OverflowError.

**Comment by pganssle** [comment]
@cedk I can try to improve the documentation about what errors can be raised, but I don't think it's a good idea to disguise the types of errors - in fact a lot of users would probably prefer distinct errors to raise distinct exceptions, so that each error can be caught independently if possible. If you want to just catch any exception raised by the code, it's better to just catch `Exception` than to force all exceptions to be `ValueError`.

For now I'm going to leave this open, because I'd like to look into avoiding this error entirely. I'm guessing it's not possible to do, but I haven't tried yet.

**Comment by pganssle** [comment]
On second thought, maybe explicitly throwing `ValueError` is the right thing to do. Hard to know, because even if arbitrarily large years were allowed by the data type, `datetime.datetime` is only valid for years up to 9999 (paging @longnow!), so it is both a `ValueError` and an `OverflowException`.

The only reason I'm still hesitating is that this is an issue with datetime *itself*, and I don't really want to preempt datetime's error handling. This seems like a low priority issue so I'll just leave it open for a while to see if we get some persuasive comments on the matter one way or the other.

**Comment by cedk** [comment]
I find that cacthing all Exception is not a very good practice because it can hide unintentional exception. So in my code, I always try to catch the expected exception. I don't care if parse raise only ValueError or also OverflowException but I think it will be better to have a clear statement on which exceptions we can expect from parse method.

**Comment by pganssle** [comment]
Yes, well I can certainly add a `:raises:` entry into the parser docstring and include the `OverflowException`, for now, though I think that this does actually happen at the point of generation of the `datetime`, so I'm going to have to make it clear that this error is not something we're raising.

Honestly, I think maybe it's worth bringing to the attention of the [python bug tracker](http://bugs.python.org), if it's not already on there (I don't think it is). It seems like this is an issue with the consistency of exceptions raised by datetime.

**Comment by cedk** [comment]
It is documented in `datetime` documentation but as we don't pass to `parse` directly a integer for the year, we don't know how `parse` will deal in such case. So yes probably adding it to the docstring will be good.

**Comment by pganssle** [comment]
Added to documentation in #63.
