### ISSUE TITLE
Fails to parse simple date string

### ISSUE THREAD

**Issue by dhirschfeld** [dateutil/dateutil#60]
Can someone confirm that I'm not going mad and that the latest version can't parse a simple date string on Python2.7, win64?!
```python
In [1]: from dateutil.parser import parser, parserinfo

In [2]: p = parser()

In [3]: p.parse('01-Jan-2015')
Traceback (most recent call last):

  File "<ipython-input-3-d4aa6116cb43>", line 1, in <module>
    p.parse('01-Jan-2015')

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 387, in parse
    res = self._parse(timestr, **kwargs)

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 487, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 174, in split
    return list(cls(s))

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 171, in next
    return self.__next__()  # Python 2.x support

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 164, in __next__
    token = self.get_token()

  File "C:\dev\bin\Anaconda\lib\site-packages\dateutil\parser.py", line 82, in get_token
    nextchar = self.instream.read(1)

AttributeError: 'str' object has no attribute 'read'
```
System details:
```python
In [6]: dateutil.__version__
Out[6]: '2.4.1'

In [7]: from IPython import sys_info

In [8]: print sys_info()
{'default_encoding': 'cp1252',
 'os_name': 'nt',
 'platform': 'Windows-7-6.1.7601-SP1',
 'sys_executable': 'C:\\dev\\bin\\Anaconda\\python.exe',
 'sys_platform': 'win32',
 'sys_version': '2.7.5 |Continuum Analytics, Inc.| (default, Jul  1 2013, 12:37:52) [MSC v.1500 64 bit (AMD64)]'}
```

**Comment by pganssle** [comment]
@dhirschfeld Rather than instantiating a `parser` object, if you use the `parse()` function it will work. Alternatively, you can `encode` the string so that it is unicode before passing it to `dateutil.parser.parser.parse()`, or use `from __future__ import unicode_literals`:

    >>>from dateutil.parser import parse, parser
    >>>p = parser()
    >>>parse('01-Jan-2015')
    datetime.datetime(2015, 1, 1, 0, 0)
    >>>p.parse(u'01-Jan-2015')
    datetime.datetime(2015, 1, 1, 0, 0)

The reason for this is that the tokenizer requires unicode strings - `parse()` has logic that handles the conversion, but this is not included in `parser.parse()` (for which `parse()` is a light wrapper). It seems reasonable to me that we could move the unicode-to-string logic into `parser.parse()` or even into `_timelex()`, but I'm not sure if that was an oversight or if there's a specific reason it was done this way. Maybe @jarondl knows.

For now, if you really need to call `parse()` on a parser object, you can validate the input string as such:

```python
    from six import binary_type       
    from dateutil.parser import parser

    p = parser()
    timestr = '01-Jan-2015'
    if isinstance(timestr, binary_type):
        timestr = timestr.decode()
    p.parse(timestr)
```

For most use cases, though, it is sufficient to pass a `parserobject` as a second (or named) argument to `dateutil.parser.parse`.

**Comment by dhirschfeld** [comment]
Thanks for following up - at least I can work around it now. A `TypeError` might be useful for Python2 users.
