### ISSUE TITLE
Full spelling of timezone fails?

### ISSUE THREAD

**Issue by apiszcz** [dateutil/dateutil#600]
Is there an approach to convert the following?
```
(Pdb) dateparse.parse('May  1, 2017 20:43:13.229000000 Eastern Daylight Time')
*** ValueError: Unknown string format

The acronym is fine.
(Pdb) dateparse.parse('May  1, 2017 20:43:13.229000000 EDT')
datetime.datetime(2017, 5, 1, 20, 43, 13, 229000)
```

**Comment by pganssle** [comment]
The 3-letter version works only because your local time zone happens to be EST and we're able to pick up the names `EST` and `EDT` from `time.tzname`. Otherwise we have no way of mapping `Eastern Daylight Time` to a specific time zone.

Normally, I'd say just add whatever zone name -> zone mappings you want in `tzinfos` and it will pick that up, but unfortunately the way we're identifying "possible zone names" precludes anything longer than ~4 characters, and expanding that definition has some knock-on effects that create other unfortunate or ambiguous parses. At some point we will rework how datetimes are parsed and this will be fixed.

In some ways this may also be related to #144.

**Comment by apiszcz** [comment]
Windows 10 is the system generating that style. Thanks.
