### ISSUE TITLE
tests missing in -2.4.1

### ISSUE THREAD

**Issue by idella** [dateutil/dateutil#65]
~/cvsPortage/gentoo-x86/dev-python/python-dateutil $ l /mnt/gen2/TmpDir/portage/dev-python/python-dateutil-2.4.1/work/python-dateutil-2.4.1/dateutil

easter.py  parser.py  relativedelta.py  rrule.py  tz.py  tzwin.py  zoneinfo  __init__.py

NO tests folder, no testsuite.

test_suite="dateutil.test.test"

How does one do this?????
This is from the tarball you uploaded to pypi.

**Comment by pganssle** [comment]
Hm. Strange. I must have done the packaging wrong, I'm not seeing it on the .zip, either, but it's in the 2.4.0 release. I used ``setup.py sdist``, I believe, as recommended by the [packaging and distributing guide](https://packaging.python.org/en/latest/distributing.html#source-distributions). Let me dig into it and see if I can fix the issue with the test suite.

For now if you want to install from source, you can clone the git repo, which does have the test suite.

**Comment by idella** [comment]
@pganssle thx.  I don't know the first thing about packaging tarballs but u have seen this oh so frequently.  Get the impression more and more the packaging for upload to pypi isn;t so easy. Really I don't know.  While I can clone the repo I don't.  What I package in ebuilds is what comes in tarballs or version releases.  What happens in the git repo I could access if I really want.

**Comment by idella** [comment]
@pganssle I have now found exactly the same thing in a package routes-2.1.
Now is this a bad habit or is this an outbreak caused by something in github or pypi itself.  All I know is that I keep bumping packages that had testsuites that no longer come with one.
 I wanna know. Who's responsible???!!!

**Comment by pganssle** [comment]
@idella I don't know about routes, but what happened here is that 2.4.1 is the first release that I prepared, and I suspect I did it differently than the other maintainers.

I was using `python setup.py sdist` generates the source distribution containing only the source actually used in the package, plus anything declared in the manifest (cuts out irrelevant metadata like say the travis configuration, etc). The problem is that the test suite is not a standard part of the module and it was not included in the manifest, so the script didn't include it. Evidently the other maintainers were creating the source distribution by some other method.

I'll manually add the test suite to the 2.4.1 source distributions and re-upload them, then add the tests to the manifest for the next release (likely 2.5.0).

**Comment by idella** [comment]
Thanks for the outline.  It appears you're far from on your own.  
<and it was not included in the manifest>
appears to be what commonly occurs.  Thank you for attending to it.

**Comment by pganssle** [comment]
@idella Actually, I think the issue may have been with my version of setuptools or something, and not with the manifest. I updated setuptools and did the source build again and it included the test suite with no changes.

I uploaded the new source distributions to PyPi under the same version number (though it made me change the file name, annoyingly - hopefully that won't cause a problem).
