### ISSUE TITLE
Version number not appearing in documentation title

### ISSUE THREAD

**Issue by rmahajan14** [dateutil/dateutil#684]
In the dateutil docs page, e.g. [rrule](http://dateutil.readthedocs.io/en/stable/rrule.html), when i hover over the tab on chrome, it says "dateutil unknown documentation". Should we change something to make it more informative?

**Comment by pganssle** [comment]
What's supposed to go there is the version number.

I'm not entirely sure why the build is succeeding at all, but I suspect that the problem is either that ReadTheDocs is not installing the package, so [this](https://github.com/dateutil/dateutil/blob/master/docs/conf.py#L60) is failing to import correctly. That said, I would think that that would cause an actual build failure, so what I think is *actually* happening is that the documentation uses the "latest" version, and for the new `setuptools_scm` setup, that looks like this:

```python
>>> from dateutil import __version__
>>> print(__version__)
2.7.3.dev24+ge35625b.d20180415
```

It may be trying to parse out a simple SemVer triplet from that and failing. One possible solution is to use `setuptools_scm` directly. It's explained how to do that [on the setuptools_scm documentation](https://github.com/pypa/setuptools_scm#programmatic-usage), but also discouraged. We can start with the `pkg_resources` example they provide there.

That said, unfortunately this is a problem specific to ReadTheDocs, and I don't really know how to test that other than by just merging stuff into master. I'll have to figure out how to get it to build against a PR for testing purposes.

**Comment by pganssle** [comment]
I think I fixed this by changing a parameter in the `readthedocs` page.

It's working on the [the "latest" build](https://dateutil.readthedocs.io/en/latest/relativedelta.html).

**Comment by rmahajan14** [comment]
Which pull request is this change a part of?

**Comment by pganssle** [comment]
It isn't a part of any pull request, it was a change to the settings of the website that hosts the documentation.

**Comment by pganssle** [comment]
Ah, actually I figured it out. If you [look here](https://github.com/dateutil/dateutil/blob/master/dateutil/__init__.py#L5), you'll see that `__version__` is always populated - it's populated with `'unknown'` if `setuptools_scm` has not done its magic, and it's populated with `._version.version` if `_version` exists.

Presumably what was happening before was that `readthedocs` was not running an install step, so `setuptools_scm` didn't run, and when it imported `__version__`, it got `unknown` rather than throwing an `ImportError`. So adding an install step fixed it.

The only remaining question is whether this can be made to work without the install step by changing the version import over to `pkg_resources.get_distribution().version` instead.

**Comment by rmahajan14** [comment]
Oh wow. Got it!
