### ISSUE TITLE
Ordering in the rrule documentation keywords explanation

### ISSUE THREAD

**Issue by rmahajan14** [dateutil/dateutil#686]
There is a difference in the order in which the arguments are listed in the function definition(at the beginning of the documentation), and the order in which they are explained. Specifically, cache is the last argument given when we are defining the function in the documentation, but is the first one to be explained.  (http://dateutil.readthedocs.io/en/stable/rrule.html). Another out-of-order keyword is byeaster.

Should we change the ordering in http://dateutil.readthedocs.io/en/stable/_modules/dateutil/rrule.html#rrule to make it consistent?

**Comment by pganssle** [comment]
Yes these should have a consistent order. Good catch.

**Comment by rmahajan14** [comment]
So, does this just involve changing the order in the code "http://dateutil.readthedocs.io/en/stable/_modules/dateutil/rrule.html#rrule" ?

So, can i just change the order and submit a PL, without running any tests explicitly from my end?

**Comment by pganssle** [comment]
@rmahajan14 For changes to the docs you should run `tox -e docs` on your end to ensure that the documentation builds correctly.

Not sure what you mean by "changing the order in the code", though. The order of the parameters needs to stay the same, because they are not keyword-only arguments. You'll want to change it in the docstring.

After that, go into `docs` and run `make html`, then you can view the documentation under the `_build` directory to ensure that your changes worked correctly.
