### ISSUE TITLE
[Feature Request] Adding the ability to disable automatic century detection

### ISSUE THREAD

**Issue by starrify** [dateutil/dateutil#703]
Currently `dateutil` would try converting two-digit years, and [here](http://labix.org/python-dateutil/#head-19e5d3331806e55ec2ba1b9e39458784cc0a0004) is the corresponding section in the doc describing its behavior.

While it's generally helpful, there're still specific cases where it's a pain. E.g. a user may want all two-digit year values to be regarded as in the 1900s.

Currently it's possible to disable automatic century detection by sub-classing the `dateutil.parser.parserinfo` class, or via a patch like this:
```
>>> import dateutil.parser
>>> dateutil.parser.parse('65-12-01')
datetime.datetime(2065, 12, 1, 0, 0)
>>> old_init = dateutil.parser._parser._ymd.__init__
>>> def new_init(self, *args, **kwargs):
...   old_init(self, *args, **kwargs)
...   self.century_specified = True
... 
>>> dateutil.parser._parser._ymd.__init__ = new_init
>>> dateutil.parser.parse('65-12-01')
datetime.datetime(65, 12, 1, 0, 0)
```

I suppose it might be a good idea to include the feature as an optional argument of `dateutil.parser.parse`.

**Comment by pganssle** [comment]
Subclassing `parserinfo` is the supported, official way to do this for the moment. I don't think that will change at any point in the future.

Anything that involves referencing a private module or attribute is incorrect.

I am explicitly attempting to move *away* from parameters passed to `parser.parse`, so that `parser.parse` can keep a nice simple interface, while its behavior is configurable in other ways. If you want something that *always* turns 2-digit years into years in the 1900s, do this:

```python
from dateutil.parser import parserinfo, parser
class parserinfo_20c(parserinfo):
    def convertyear(self, year, century_specified=False):
        if not century_specified and year < 100:
            year += 1900
        return year

parser_20c = parser(parserinfo_20c())

def parse_20c(timestr, **kwargs):
    return parser_20c.parse(timestr, **kwargs)
```

Or some other variation on that.
