### ISSUE TITLE
Unexpected / inconsistent behavior - parse() accepts a string of an integer as input

### ISSUE THREAD

**Issue by ryantuck** [dateutil/dateutil#718]
`parse()` accepts a string with an integer value, whereas i would expect it to throw an exception. 

In addition, the behavior is not consistent - if the integer can be assigned as the day of month, it will be, and otherwise it will be assigned to the year, and default to the current month and day.

```
$ ipython
Python 3.6.4 (default, Mar  9 2018, 23:15:12)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import dateutil

In [2]: dateutil.__version__
Out[2]: '2.7.2'

In [4]: from dateutil.parser import parse

In [5]: parse('5')
Out[5]: datetime.datetime(2018, 5, 5, 0, 0)

In [8]: parse('4')
Out[8]: datetime.datetime(2018, 5, 4, 0, 0)

In [9]: parse('32')
Out[9]: datetime.datetime(2032, 5, 9, 0, 0)

```

**Comment by pganssle** [comment]
Generally speaking with the `parser` the contract is that you are passing something that *does* represent a datetime, and we're giving you our best guess as to how to interpret it (with minimal context). Do not use `dateutil.parser.parse` to validate whether or not something *does* represent a `datetime`, as that question requires a lot more context than we can really give it.

For example, what if you were writing a chatbot and had this interchange:

```
BOT: What year were you born in?
HUMAN: 1975
```

1975 is a year, if you want to make it a `datetime` you can pass it to `dateutil.parser.parse` and it will work, so we can't throw away *all* integers-as-strings. Hopefully changes to the interface in the future will allow us to give you access to more of the machinery of the parser so that, if desired, you can write a custom datetime validator using the parser logic.
