### ISSUE TITLE
min day when add is unreasonable

### ISSUE THREAD

**Issue by yuetingqian** [dateutil/dateutil#808]
https://github.com/dateutil/dateutil/blob/a5d860d370a8486fdbcd338c244dc5f583beba5f/dateutil/relativedelta.py#L377~L378

testcase as follower:
```
import datetime
end = datetime.datetime(2018, 8, 28) + relativedelta(months=+6)
print end
end = datetime.datetime(2018, 8, 29) + relativedelta(months=+6)
print end
end = datetime.datetime(2018, 8, 30) + relativedelta(months=+6)
print end
```
both output
```
2019-02-28 00:00:00
2019-02-28 00:00:00
2019-02-28 00:00:00
```

I think it's not unreasonable to return the same date when different start_date add the same months.

It should be like this
```
2019-02-28 00:00:00
2019-03-01 00:00:00
2019-03-02 00:00:00
```

**Comment by pganssle** [comment]
@yuetingqian This is working as intended. Months are not a fixed number of days, so saying "six months from X" is ambiguous. There are four reasonable behaviors for what happens when you attempt to advance a datetime by a certain number of months and land on a non-existent datetime (e.g. February 31st):

1. Fall back to the most recent valid day (February 28/29)
2. Fall forward to the *next* valid day (March 1st)
3. Push to the next month and set the day to be the number of days of that month, mod the last day of the month you were coming from (March 3rd/4th)
4. Raise an error.

For the most part, people want behaviors 1 or 2. I find it unlikely that behavior 3 would be amazingly useful, because it's a strange mixture of "fixed number of days offset" (which can be handled with `timedelta(days=N)` or `relativedelta(days=N)` and "number of months offset".

The main reason I could see for wanting this behavior is if you want to chain together multiple addition operations, which is a known issue, but one we can really do nothing about without destroying the utility of people who want 1 and 2.

I believe it's easy enough to accomplish what you want, though:

```python
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

def rd_add_months(dt, N):
    dto = dt + relativedelta(months=N)
    if dto.day != dt.day:
        # When adding a relative number of months, the resulting
        # day should only be different if the number of days in
        # the start and end months are different, in which case the
        # output date will be pinned to the END of the month.
        dto += timedelta(days=(dt.day % dto.day))

    return dto

for d in range(28, 31):
    print(rd_add_months(datetime(2018, 8, d), 6))
```

**Comment by yuetingqian** [comment]
ok thank you
