### ISSUE TITLE
Did the weekday type change? I can't hash or compare

### ISSUE THREAD

**Issue by reagle** [dateutil/dateutil#815]
In a python2.7 script, I have a function that, given today, returns the last day class met. I haven't used the script in about 5 months. When I went to do so today, the code failed. The interpreter says type 'weekday' is not hashable and I cannot compare if `TU <= FR`. Did something change in the last few months? 

```python
import time
from datetime import *     # https://docs.python.org/2/library/datetime.html
from dateutil.tz import *
from dateutil.parser import *    # http://labix.org/python-dateutil
from dateutil.relativedelta import * # includes MO TU WE TH FR SA SU

def get_previous_class(classes, today):
    '''returns previous class by finding the scheduled class days
    of the week before today, and selecting the max/latest.

    >>> get_previous_class((TU, FR), MO)
    FR
    >>> get_previous_class((TU, FR), WE)
    TU
    >>> get_previous_class((TU, FR), FR)
    TU
    >>> get_previous_class((TU, FR), SA)
    FR    
    '''
    
    info(" classes = '%s' today = '%s'" %(str(classes), today))
    # if today's day precedes this week's class days act as if 
    # I'm a week ahead -- this is simpler than moving classes back a week
    if today <= sorted(classes)[0]:     
        today = SA
        info(" today adjusted = %s" % today)
    c_list = []

    # previous_class = max([c for c in classes if c < today])
    for c in classes:
        info(" testing if %s < %s" %(c, today))
        if c < today:
            c_list.append(c)
            info("True")
            info("append c_list.append(%s)"%c)
        else:
            info("False")
    info(" c_list = '%s'" %c_list)
    info("type(c_list) = '%s'" %type(c_list))
    previous_class = max(c_list)
    
    info(" previous_class = %s " % previous_class)
    return previous_class
```

**Comment by pganssle** [comment]
I don't think that script is sufficient to actually run the program, but `weekday` objects are not comparable and I don't think they ever were intended to be. It is likely a quirk of Python 2 that allowed this script to "work" at all in the sense that the comparison operators were not explicitly defined and I think in Python 2 comparison falls back to object id, which is not the semantics you want at all.

You are not really supposed to use weekday objects like this, they are more like fancy Enums for use with `relativedelta` and `rrule`.

FWIW, your script still seems to "work" in Python 2.7 for me, so it may be you're invoking this with Python 3 and didn't realize it, or maybe this script doesn't actually reproduce the behavior you mention (I had to add `from logging import info` at the top of the page, so maybe the bug is somewhere else).

Some recommendations for your script:

1. Define your own weekday types, you can get the semantics you want pretty easily like this:

```python
MO, TU, WE, TH, FR, SA, SU = range(7)
```

That said, note that this gives a specific ordering to the days of the week that isn't universal. Monday is "less than" Sunday, but in some locales the week starts on Sunday. I would have hoped that `calendar`'s weekday objects would be locale-sensitive, but it seems that `calendar.MONDAY < calendar.SUNDAY` even if you change the locale with `calendar.setfirstweekday(calendar.SUNDAY)` or whatever.

2. I would recommend against star imports like you're doing here. If you had `rrule` and `relativedelta` in this list, you could get some values shadowing one another, and it's just generally not a good idea - hard to tell where your symbols are coming from.

3. The documentation for `dateutil` is actually at https://dateutil.readthedocs.io now. The labix.org documentation is horribly out of date.

Good luck with your script!

**Comment by reagle** [comment]
@pganssle, thank you for the thorough answer. I think what changed in the last five months is python3 became the default on my system and it triggered a few bugs in this old script. I've moved everything else to python3, so knowing this was never supported behavior will help the migration. 

I was also surprised to see the star imports, which I no longer do, but I see I probably picked them up from the documentation, where they are still [very common](https://dateutil.readthedocs.io/en/stable/examples.html).

**Comment by pganssle** [comment]
Ah yes, they are distressingly common in the documentation (and in documentation in general). It's very convenient to use star imports in docs because it makes the examples much shorter, but I fear it does set a bad example.

**Comment by reagle** [comment]
I haven't looked at these libraries in a long time, so I hope you don't mind if I ask for a hint. `get_previous_class()` was actually called by `get_previous_class_date()` where I took advantage of the fact that these seemed to be ordinal types and I could also use them within datetime calculations.

```
    prev_class_date = now+relativedelta(    # since 6PM day of last class
        hour=18, minute=0, second=0, weekday=prev_class(-1))
```

I'm sure there are other bugs in the py2 to py3, but I'm wondering how to best approach the above.

```
# Date stuff ##############################

MO, TU, WE, TH, FR, SA, SU = range(7)
INT2DAY = {0: MO, 1: TU, 2: WE, 3: TH, 4: FR, 5: SA, 6: SU}


def get_previous_class(classes, today):
    '''returns previous class by finding the scheduled class days
    of the week before today, and selecting the max/latest.

    >>> get_previous_class((TU, FR), MO)
    FR
    >>> get_previous_class((TU, FR), WE)
    TU
    >>> get_previous_class((TU, FR), FR)
    TU
    >>> get_previous_class((TU, FR), SA)
    FR

    '''

    info(" classes = '%s' today = '%s'" % (str(classes), today))
    # if today's day precedes this week's class days act as if
    # I'm a week ahead -- this is simpler than moving classes back a week
    if today <= sorted(classes)[0]:
        today = SA
        info(" today adjusted = %s" % today)
    c_list = []

    # previous_class = max([c for c in classes if c < today])
    for c in classes:
        info(" testing if %s < %s" % (c, today))
        if c < today:
            c_list.append(c)
            info("True")
            info("append c_list.append(%s)" % c)
        else:
            info("False")
    info(" c_list = '%s'" % c_list)
    info("type(c_list) = '%s'" % type(c_list))
    previous_class = max(c_list)

    info(" previous_class = %s " % previous_class)
    return INT2DAY[previous_class]


def get_previous_class_date():
    '''returns previous class in time format'''

    now = datetime.now(tzlocal())    # could use (pytz.timezone('US/Eastern'))
    now_day = now.today().weekday()
    info("now_day = %s" % now_day)
    prev_class = get_previous_class((TU, FR), now_day)
    info("prev_class = %s" % prev_class)
    prev_class_date = now+relativedelta(    # since 6PM day of last class
        hour=18, minute=0, second=0, weekday=prev_class(-1))
    info("prev_class_date = %s" % prev_class_date)
    return prev_class_date
```

**Comment by pganssle** [comment]
@reagle 

A few things:

```python
now_day = now.today().weekday()
```

The `today` is unnecessary. `datetime.today` is an alternate constructor for `datetime` that returns the same thing as `now`.


Also:

```python
MO, TU, WE, TH, FR, SA, SU = range(7)
INT2DAY = {0: MO, 1: TU, 2: WE, 3: TH, 4: FR, 5: SA, 6: SU}
```

I'm guessing you want a mapping between the integer values you just defined and the `relativedelta` components, but what you've actually done is mapped the integers 0-7 to themselves.

I think you want some thing more like this:

```python
from dateutil import relativedelta as rd
INT2DAY = {i: day for i, day in enumerate((rd.MO, rd.TU, rd.WE, rd.TH, rd.FR, rd.SA, rd.SU))}
DAY2INT = {v: k for k, v in INT2DAY.items()}
MO, TU, WE, TH, FR, SA, SU = INT2DAY.keys()
```

That gives you a bidirectional mapping between `relativedelta`'s weekday objects and the integers (discard one of the directions if you don't need it). You can then just change `get_previous_class_date` to work like this:

```python
prev_class_date = now+relativedelta(    # since 6PM day of last class
    hour=18, minute=0, second=0, weekday=INT2DAY[prev_class](-1))
```

If the fact that these day objects are the `dateutil` objects is really built deeply into your codebase, you can leave them as is and instead of using `INT2DAY` on the output of `get_previous_class`, you would use `DAY2INT` on its *inputs* and `INT2DAY` on the value before you return it.

Also, I notice a comment about `pytz` in there. [Here is a blog post I wrote](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html) about the differences between `dateutil` and `pytz`.
