### ISSUE TITLE
Parser only partially accounts for case-insensitive nature of ISO8601 datestamps

### ISSUE THREAD

**Issue by cjgibson** [dateutil/dateutil#820]
```bash
$ python -c "from dateutil.parser import parse
> print parse('1970-01-01T00:00:00Z')
> print parse('1970-01-01t00:00:00Z')
> print parse('1970-01-01t00:00:00')
> print parse('1970-01-01t00:00:00z')"
1970-01-01 00:00:00+00:00
1970-01-01 00:00:00+00:00
1970-01-01 00:00:00
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

It looks like this library properly supports both the use of `t` and `T` as legal time separators for ISO8601 datestamps, but only supports the uppercased shorthand for UTC (`Z`), and not `z`. From what I can find online (namely, this RFC: https://tools.ietf.org/html/rfc3339#section-5.6), it seems like the latter is also legal syntax.

**Comment by pganssle** [comment]
If true that the ISO 8601 format allows for `z`, then we should at the very least update `dateutil.parser.isoparse`.

I don't know if we need to or want to add support for this in `dateutil.parser.parse`. The obvious way to do so would be to change `parserinfo.UTCZONE` to include `'z'`, but I suspect a lower-case z is more often there for some reason *other* than because the datetime is supposed to be in UTC. Anyone who knows they have a `z` can always create a modified `parserinfo` if they run into this problem.

That said, one thing I was considering for the long term is refactoring `dateutil.parser.parse` to use `dateutil.parser.isoparse` *first*, and fall back to the regular parser if the parse fails. In that case, `YYYY-MM-DDtHH:MM:SSz` would be accepted, but `Dec 19, 2018 10:30z` would not be, which I'm kinda OK with.

@jbrockmendel Thoughts? Am I overthinking this? Should we just add `'z'` to the default UTCZONE?

**Comment by pganssle** [comment]
@jbrockmendel OK, I agree.

Take-away for anyone who wants to make a PR:

1. Change the `Z` detection to detect `z` as well in `dateutil.parser.isoparse`
2. Add `z` to `UTCZONE`.

The only remaining uncertainty I have is whether we should make `UTCZONE` case-insensitive. I'm thinking maybe in a future version we can have that, but with a switch to turn it off.
