### ISSUE TITLE
dateutil isoparser in Go - interest in adding to organization page?

### ISSUE THREAD

**Issue by bsolomon1124** [dateutil/dateutil#821]
Hello @pganssle.  I recently ported the code and and corresponding tests from `isoparser.py` to [Go](https://golang.org/), partly as my own means to better learn the language and partly because the functions in that module are well suited to a statically typed language.  (Though the Python version is already impressively fast.)

I realize that pretty much the entirety of this module is your work; would you be interested in adding the Go package under the dateutil GitHub organization?  The Go package is currently private, but I would be glad to share with you if you'd like to take a look over it.  My email is bsolomon@protonmail.com.

**Comment by pganssle** [comment]
@bsolomon1124 I'm glad the isoparser could be helpful to you. It was at least partially designed with static languages in mind, since I'm hoping to start with this and/or the time zone logic for a first pass at adding a compiled backend to `dateutil`. I wrote a version of this with Cython and C (the latter of which formed the core of [CPython's `datetime.fromisoformat`]).

As for adding the `go` version to the `dateutil` organization, I think it's probably not a good idea, since I don't think there's a lot of reason to put them under the same umbrella - most Python dateutil maintainers will not really be able to help with the maintenance of any golang version and vice versa, so there's no real reason for shared permissioning. I also think the people interested in one will not necessarily look in the Python organization for a golang module.

That said, if you do publish it somewhere please send me a link (either by e-mail or by adding it to this issue). At some point it might be nice to add a collection of "ports and modules inspired in other languages" or something to the documentation.

**Comment by bsolomon1124** [comment]
@pganssle Thanks for considering and you raise a valid point regarding maintenance.  I'm going to add some additional tests and then will likely upload to my own GitHub page with proper attribution and will let you know when I do.

**Comment by bsolomon1124** [comment]
@pganssle FYI, I've added a Go version of `isoparser.py` at https://github.com/bsolomon1124/isoparse.  It is passing all tests, most of which were replicated from `test_isoparser.py`.

I also made a point of citing you as the original author and offering the disclaimer that the two may not mirror, align, or track each other perfectly going forward.
