### ISSUE TITLE
README.rst: the 'Quick example' is not shown

### ISSUE THREAD

**Issue by goetzc** [dateutil/dateutil#83]
When https://github.com/dateutil/dateutil is seen from a web browser, the 'Quick example' is not shown.

**Comment by pganssle** [comment]
Yes, I've tried to fix this. The problem is that Github does not support the sphinx doctest module, and the readme is transcluded in the ReadTheDocs documentation (which does include doctest). I'm trying to avoid duplicating the text, but I haven't found a mechanism to specify fallback text on failure.

It's possible we could switch it from being a doctest, of course, especially since the doc tests aren't included in the CI, but I'd rather move towards including doctests in the test suite, rather than away from that.

**Comment by pganssle** [comment]
Github seems to have fixed this all on their own.
