### ISSUE TITLE
Cannot install dateutil from sources starting from dateutil==2.7.1

### ISSUE THREAD

**Issue by tvalentyn** [dateutil/dateutil#840]
Here's a repro from a virtual environment:

```
$ pip freeze --all

pip==18.1
setuptools==40.6.2
wheel==0.32.2

$ python -m pip download --dest /tmp python-dateutil==2.7.1 --no-binary :all: --no-deps

$ pip install /tmp/python-dateutil-2.7.1.tar.gz --no-index 

Processing /tmp/python-dateutil-2.7.1.tar.gz
  Installing build dependencies ... error
  Complete output from command /tmp/myenv/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vNkVo1 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- setuptools>=38.2.5 wheel:
  Collecting setuptools>=38.2.5
    Could not find a version that satisfies the requirement setuptools>=38.2.5 (from versions: )
  No matching distribution found for setuptools>=38.2.5
  
  ----------------------------------------
Command "/tmp/myenv/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vNkVo1 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- setuptools>=38.2.5 wheel" failed with error code 1 in None
```

Do you have any ideas why starting from version 2.7.1 during installation of python-dateutil we happen to run this command `/tmp/myenv/bin/python -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-vNkVo1 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- setuptools>=38.2.5 wheel`? 

Due to `--ignore-installed` flag, it fails, even though `setuptools` and `wheel` dependencies are installed in the virtual environment. 2.7.0 does not have this behavior.

**Comment by sebix** [comment]
That's a virtualenv change, they now don't use the system's libraries by default anymore.

Use `--system-site-packages` in the virtualenv creation to change this

**Comment by pganssle** [comment]
This is very strange. I don't think `--system-site-packages` should help, and indeed it does not.

I'm guessing the problem, such that it is one, that in version 2.7.1, we [added  `long_description_content_type`](https://github.com/dateutil/dateutil/pull/648), which bumped the `PKG-INFO` metadata from version 1.2 to 2.1. `pip` or whatever is detecting that the metadata is version 2.1 and attempting to install a version of `setuptools` that matches the version `>=38.2.5`, and since you have `--no-index` it is not allowed to find that on PyPI.

Evidently `pip`'s version of `setuptools` is too low to handle 2.1 so it attempts to install a higher version of `setuptools` in the isolated build environment, cannot find one in whatever sources it's allowed to look at (maybe the cache?) for whatever reason, and fails. 

If `--no-index` matters to you more than build isolation, you can solve this by using `--no-build-isolation`:

```bash
pip install python-dateutil-2.7.1.tar.gz --no-build-isolation --no-index
```

I'm not quite sure why it can't find a matching version of `setuptools`, though. I suggest maybe opening an issue on `pip`. Feel free to CC me.
