### ISSUE TITLE
Cannot parse correct year

### ISSUE THREAD

**Issue by OmkarPathak** [dateutil/dateutil#847]
I have a string as:
```
Supervised and trained a staff of 10-30 team members Education MS, Analytics University of San Francisco, July 2015
```
Parser outputs the following Date:
```
July-2010
```
While the actual date is **July 2015**

With `fuzzy_with_tokens=True`:
```
(datetime.datetime(2010, 7, 30, 20, 15)
```

Any workarounds? It is taking 10-30 into consideration too!

**Comment by ffe4** [comment]
The parser expects that you give it something resembling a date, but only a small fraction of your input is related to the date. The parser also does not do natural language processing. It does not try to parse the meaning of your sentence, instead it tries to find tokens which could be part of the date. The benefit of fuzzy parsing is that it ignores invalid tokens without returning an error. `10-30` is a token that would very likely be part of the a date string, and its surrounding context gets ignored. You essentially end up parsing `10-30 July 2015`, which is intended.

As for why this is parsed to `datetime.datetime(2010, 7, 30, 20, 15)`, my best guess is that the parser knows that `July` represents the month, and assumes that `10-30` much be the rest of the date, since the hours and minutes usually are not separated by a hyphen. Then `2015` has to be the time.

The main problem is that your input is not what the parser is meant do parse, and I think for the expected inputs the behavior is unlikely cause issues. Part of this question could probably be addressed via improvements to the parser documentation (#26, #666)
