### ISSUE TITLE
Would it be possible to release 2.4.3?

### ISSUE THREAD

**Issue by pquentin** [dateutil/dateutil#89]
I just encountered a bug that was fixed in master, but not in 2.4.2: `parser.parse('2015-04')` throws `ValueError` when the current day is 31, which was the case yesterday, May 31st.

Is it possible to release a new version that includes the fix? I could help with the release if needed/possible. Thanks!

**Comment by pganssle** [comment]
@pquentin I'm not sure this justifies an immediate release by itself, since it only occurs on the 29th, 30th and 31st of the month. I think there's a decent set of new features and bug fixes for a 2.5.0 release, so maybe we can set a goal of having 2.5.0 out either by the end of June or the end of July.

@jarondl Any disagreement?

**Comment by pquentin** [comment]
@pganssle concerning the release number, I don't think waiting for bigger features is a good reason not to release early&often. Release numbers are less and less relevant these days.

But that's OK, because I've decided to use https://pypi.python.org/pypi/iso8601 first, and only use dateutil if iso8601 raises a ParseError exception, for two main reasons:
 * I don't expect the result of `parse(2009-04)` to change with the current day: using 1 as the day is the result I would have expected
 * ISO 8601 is unambiguous, and a valid ISO 8601 string is unlikely to mean something else
 * (Bonus: It works today without using a git dependency link in setup.py, which is deprecated by pip and should have been removed in pip 7 already.)

Maybe doing this directly in dateutil could make sense, but I imagine you have good reasons for not doing so. Anyway, I'm sorry for the noise, and will close the issue.

Many thanks for the quick answer!

**Comment by pganssle** [comment]
@pquentin I just meant that an immediate release is not important because the bug only happens on certain days of the month, and we happen to be in a 30-day month anyway, so it's not likely to affect much of anything before we get a chance to do a proper feature release anyway.

Note that this bug only occurs when using the default argument for the default date. If you use, e.g. `parse('2014-04', default=datetime(2015, 05, 31))`, you'll get an error no matter what day you run the command on, whereas if you use `parse('2014-04', default=datetime(2015, 05, 01))`, you'll never get an error. You can use a hybrid approach by using `parse('2014-04', default=datetime.today().replace(day=1))`, which returns the first of a given month when no day is specified.

**Comment by pquentin** [comment]
Thanks for the tip!
