### ISSUE TITLE
dateutil.parser.parse allows unrealistic timezones

### ISSUE THREAD

**Issue by bnlerner** [dateutil/dateutil#919]
timezone offsets of greater than and less than or equal to 12 is not realistic and should not be allowed. Compliance to this standard prevents errors in other systems 

Failure case
```python
from dateutil import parser

timestamp = '2019-05-23T09:13:08.080000+1623'
datetime_fmt = "%Y-%m-%dT%H:%M:%S.%f%z"

parser.parse(timestamp).strftime(datetime_fmt)

```

**Comment by pganssle** [comment]
`dateutil` will need to support all time zones supported by the Python language itself (and theoretically someone could use some crazy "unrealistic" time zone for some reason at which point our software would be simply broken), regardless of how likely the offsets are to actually exist, so I'm inclined to say that this will not change.

Certainly we cannot ban offsets outside the range [-12, 12], since time zones like `Pacific/Kirimati` are real places that actually use offsets outside that range (currently Kiribati and I believe several other Pacific islands use UTC+14).

However, if you can provide an example of a string where a part of the string *not* intended to be interpreted as an offset (and with a value that is "unrealistic" for a time zone) is being interpreted erroneously as an offset, it may be worth looking into using an "is it realistic" heuristic to determine how to handle the parse.

That said, even that is a bit unlikely, because it tends to create paths that give the right value sometimes and the wrong value at other times - similar to the situation where `YYMMDD` values will always be interpreted correctly for YY > 31 and DD > 12, but may get it wrong in the ambiguous case. I prefer to have a fixed behavior so that people can at least work around it without too much fuss.

**Comment by bnlerner** [comment]
Understood. The problem ends up being when these time zones need to be accepted by other software, Example Postgres. Right now these time zones are rejected and a work around code to check this would need to be developed to catch this exception. If there isn’t an appetite to cap it at current listed time zones [-12,+14] we can develop this exception handling but thought I would raise it here first.

**Comment by pganssle** [comment]
@bnlerner Yeah, I think that in general to handle that on whatever adapters you have that are being passed to postgres. If Postgres or some other software restricts the domain of possible offsets to [-12, +14], I wouldn't be surprised if they also don't accept offsets like `-05:11:12.133473`, which is also a valid offset for a Python time zone.

Since `dateutil` really just translates strings into Python `datetime` and `tzinfo` objects, we're really only concerned with making sure that that translation is done accurately. If you need to pass those into software that has a different contract than the one set out in Python's `datetime` module, it should likely be done closer to the thing that's actually likely to object to it.
