### ISSUE TITLE
Pip packaging data consistency issue

### ISSUE THREAD

**Issue by gatewaynode** [dateutil/dateutil#936]
So here is an interesting data integrity problem for the Python community. Running:

pip install python-dateutil

Actually installs:

python_dateutil... .whl
Which when unzipped reveals:

dateutil
python_dateutil....dist-info
Is it possible to get this cleaned up and consistent given the #5 most used package positition?

IMHO. Date Util should be renamed just date_util(underscore, not dash per pep-8) everywhere, the wheel should be named date_util... .whl and the zipped components inside should be the dirs date_util and date_util.dist-info.

**Comment by gatewaynode** [comment]
Also this might be related to this package ignoring the "--no-deps" flag in pip.

**Comment by sebix** [comment]
> IMHO. Date Util should be renamed just date_util(underscore, not dash per pep-8) everywhere, the wheel should be named date_util... .whl and the zipped components inside should be the dirs date_util and date_util.dist-info.

pip replaces dashes with underscores / treats them the same

>  Which when unzipped reveals:
> 
> dateutil
> python_dateutil....dist-info

dateutil is the name of the module, and the name you are using to import it

The inconsistency I see is that the package name is python-dateutil instead of just dateutil. But I am sure that has been discussed a lot in the past.

**Comment by pganssle** [comment]
I think this is more of a problem for the packaging ecosystem. It would be very nice if we could change the package name from `python-dateutil` to `dateutil`, but too many people have already specified their dependencies as `python-dateutil`.

I'd be comfortable switching over to the package being named `dateutil` if we could make `python-dateutil` an alias for `dateutil`, but that's not immediately possible at the moment, and I think it could lead to weird edge cases when two names refer to the same package. Since we also own the `dateutil` package there's no possibility of typo-squatting, so we'll just leave it as an unfortunate rough edge.

**Comment by anowlcalledjosh** [comment]
It would be easy enough to write a tiny stub package that depends on `dateutil` and upload it as `python-dateutil`, surely? Yes, it would require synchronisation of uploads between `dateutil` and `python-dateutil` to avoid dependency issues (unlike [`bs4`](https://pypi.org/project/bs4/), which just depends on any version of [`beautifulsoup4`](https://pypi.org/project/beautifulsoup4/)), but if there is already automation for uploading new dateutil versions, it could be relatively easily built into that.

**Comment by pganssle** [comment]
@anowlcalledjosh This would mean that there are two different packages that would *both* get installed if one package depends on `dateutil` and another package depends on `python-dateutil`. Those two packages wouldn't necessarily be in sync and could step on each others' toes (since they'd be installing probably mostly the same files). It could easily create a *huge* mess in your environment.

A slightly better way to do it would be a dependency-only package, where `dateutil` simply depends on `python-dateutil`, but that could cause problems with version pinning (we'd need a new `dateutil` version for every `python-dateutil` in addition to the other edge cases that I alluded to with proper support for alias packages.

At this point, the ecosystem does not have good support for a transition like this at the moment, though that might change in the future. Even then, though, it would have to be really quite smooth to be worth it.

A more feasible situation would be to add an "advertising" package to PyPI at `dateutil` that tells you which version to install, but again I'd rather not put in a weird hack like that, it would be better to get official PyPI support for something of that nature.

**Comment by anowlcalledjosh** [comment]
@pganssle Sure, having two duplicate packages is a bad idea; my idea was what you describe in your second paragraph.
