### ISSUE TITLE
_DatetimeWithFold needs a nanosecond attribute for Pandas compatibility

### ISSUE THREAD

**Issue by gpshead** [dateutil/dateutil#941]
`pandas._libs.tslibs.conversion.convert_datetime_to_tsobject` requires a `nanosecond` attribute.

**Comment by pganssle** [comment]
@gpshead This is actually a bug in `pandas`, it was fixed in pandas-dev/pandas#25851. It is not that `pandas` requires a `nanosecond` attribute but that `pandas` assumes that anything in a datetime column that is not *exactly* a `datetime` is a `pandas.Timestamp` object (in that one part of the code, anyway), which is a faulty assumption. I do not think that mocking out some aspects of the `Timestamp` interface is the right thing to do at all.

If you cannot upgrade to the latest version of `pandas` and you are affected by this issue, I believe that converting your datetimes to `UTC` before passing them to `pandas` (at which point you can convert the timestamp column back to whatever timezone you desire) should be a reasonable workaround. If I understand the `pandas` model correctly, under the hood all datetimes are stored as UTC anyway, so this is not too far from the truth.

**Comment by gpshead** [comment]
oh nice, i couldn't find a reference to the problem on the pandas side when I went looking and had a hard time following their code's complicated "accept every possible type and do something with it" logic.
