### ISSUE TITLE
Support relativedelta in rrule

### ISSUE THREAD

**Issue by rafa-guedes** [dateutil/dateutil#964]
Would it be possible / make sense to allow using a `relativedelta` object as the `freq` argument (or perhaps another arg) to run rrule? So that these two would be equivalent:

```
from dateutil.relativedelta import relativedelta
from dateutil.rrule import rrule, MONTHLY

times = rrule(
    freq=MONTHLY,
    count=1,
    dtstart=datetime.datetime(2012, 1, 1),
    until=datetime.datetime(2012, 3, 1),
)

times = rrule(
    freq=relativedelta(months=1),
    dtstart=datetime.datetime(2012, 1, 1),
    until=datetime.datetime(2012, 3, 1),
)
```

**Comment by pganssle** [comment]
Thank you for your suggestion! RRULE is actually based on an IETF specification, [RFC 5545](https://tools.ietf.org/html/rfc5545), which does not map neatly onto the concept of a `relativedelta` (at least not in the "freq" portion of it). RRULE is a very complicated way of specifying datetimes, though, so you can almost always express what you want without resorting to `relativedelta`. The advantage of doing so is that because it's a standardized format, you can export it for use with other languages or standard file formats!

**Comment by maurerle** [comment]
Hi @pganssle , I think you missed the idea of this feature:
It is well understood, that RRULE is based on the standard - that should not change.
And of course
> you can almost always express what you want without resorting to relativedelta

But sometimes you have a relativedelta and need to create a standard conform rrule from that?
Currently I have to reassemble the objects myself if I am not mistaken?
I think some form of `rrule.from_relativedelta(relativedelta, start_time, until, ...)` would be quite cool therefore?

Maybe this also exists in an easy way.
Thank you!
