### ISSUE TITLE
Incorrect division(e.g. relativedelta(minutes=1) / 2)

### ISSUE THREAD

**Issue by ZacBi** [dateutil/dateutil#996]
Today I tried to type statements below but the result was weird.

```python
>>> relativedelta(minutes=1) / 2
relativedelta()
```
So I looked into the code and found that:
https://github.com/dateutil/dateutil/blob/110a09b4ad46fb87ae858a14bfb5a6b92557b01d/dateutil/relativedelta.py#L570-L578

continued:

https://github.com/dateutil/dateutil/blob/110a09b4ad46fb87ae858a14bfb5a6b92557b01d/dateutil/relativedelta.py#L495-L516

Is `int()` operation necessary?

**Comment by benhowes** [comment]
I've just had this problem with multiplication, e.g. `relativedelta(days=1) * 1.5 == relativedelta(days=1)`, though I can see it's always been like this. Making a change to that behaviour would have to be considered a breaking change too, because some people are probably relying on that behaviour.

As such, I've just made this for my use case:

```python
import warnings
from dateutil.relativedelta import relativedelta


class delta(relativedelta):
    def __mul__(self, other):
        try:
            f = float(other)
        except TypeError:
            return NotImplemented

        if int(f) != f and (self.years or self.months):
            warnings.warn(
                "Years and months can only be multiplied by integer amounts, trucating"
            )

        return self.__class__(
            years=int(self.years * f),
            months=int(self.months * f),
            days=self.days * f,
            hours=self.hours * f,
            minutes=self.minutes * f,
            seconds=self.seconds * f,
            microseconds=self.microseconds * f,
            leapdays=self.leapdays,
            year=self.year,
            month=self.month,
            day=self.day,
            weekday=self.weekday,
            hour=self.hour,
            minute=self.minute,
            second=self.second,
            microsecond=self.microsecond,
        )
```

This raises a warning if you multiply the int only fields by a float, as well as allowing the other fields to be multiplied by non-integer fields.

I'd be happy to make this a PR if people want to use it, but as I mentioned, with it being a breaking change, it would have to be for dateutil 3.0 I suspect.

**Comment by ZacBi** [comment]
@benhowes  Thanks for your solution. :smile:
